//! Kerberos Error Codes (RFC 4120 7.5.9)

/// Kerberos error codes
#[repr(i32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ErrorCode {
  None = 0,
  KdcErrNameExpired = 1,
  KdcErrServiceExpired = 2,
  KdcErrBadPvno = 3,
  KdcErrCOldMasterKvno = 4,
  KdcErrSOldMasterKvno = 5,
  KdcErrCPrincipalUnknown = 6,
  KdcErrSPrincipalUnknown = 7,
  KdcErrPrincipalNotUnique = 8,
  KdcErrNullKey = 9,
  KdcErrCannotPostdate = 10,
  KdcErrNeverValid = 11,
  KdcErrPolicy = 12,
  KdcErrBadoption = 13,
  KdcErrEtypeNosupp = 14,
  KdcErrSumtypeNosupp = 15,
  KdcErrPadataTypeNosupp = 16,
  KdcErrTrtypeNosupp = 17,
  KdcErrClientRevoked = 18,
  KdcErrServiceRevoked = 19,
  KdcErrTgtRevoked = 20,
  KdcErrClientNotYetValid = 21,
  KdcErrServiceNotYetValid = 22,
  KdcErrKeyExpired = 23,
  KdcErrPreAuthFailed = 24,
  KdcErrPreAuthRequired = 25,
  KdcErrServerNomatch = 26,
  KdcErrMustUseUser2user = 27,
  KdcErrPathNotAccepted = 28,
  KdcErrSvcUnavailable = 29,
  KrbApErrBadOption = 30,
  KrbApErrTktExpired = 31,
  KrbApErrTktNyv = 32,
  KrbApErrRepeat = 33,
  KrbApErrNotUs = 34,
  KrbApErrBadmatch = 35,
  KrbApErrSkew = 36,
  KrbApErrBadaddr = 37,
  KrbApErrBadversion = 38,
  KrbApErrMsgType = 39,
  KrbApErrModified = 40,
  KrbApErrBadorder = 41,
  KrbApErrBadkeyver = 44,
  KrbApErrNokey = 45,
  KrbApErrMutFail = 46,
  KrbApErrBaddirection = 47,
  KrbApErrMethod = 48,
  KrbApErrBadseq = 49,
  KrbApErrInappCksum = 50,
  KrbErrGeneric = 60,
  KrbErrFieldToolong = 61,
  KdcErrClientNotTrusted = 62,
  KdcErrKdcNotTrusted = 63,
  KdcErrInvalidSig = 64,
  KdcErrKeyTooWeak = 65,
  KdcErrCertificateRevoked = 72,
  Unknown = -1,
}

impl ErrorCode {
  pub fn from_i32(v: i32) -> Self {
    match v {
      0 => Self::None,
      6 => Self::KdcErrCPrincipalUnknown,
      7 => Self::KdcErrSPrincipalUnknown,
      25 => Self::KdcErrPreAuthRequired,
      _ => Self::Unknown,
    }
  }
}
