// @generated by scripts/generate-sdk-surface.js
// Manifest-driven route typing contract. Do not edit manually.

export type GeneratedCanonicalRoutePath =
  | "access/system/file"
  | "access/system/network"
  | "access/system/process"
  | "access/system/registry"
  | "access/system/service"
  | "agent/c2/connect"
  | "agent/c2/server"
  | "assess/target/run"
  | "assess/target/show"
  | "attack/target/apt"
  | "attack/target/plan"
  | "attack/target/playbooks"
  | "attack/target/run"
  | "auth/test/http"
  | "bench/load/run"
  | "bench/load/stress"
  | "binary/analysis/checksec"
  | "binary/analysis/find"
  | "binary/analysis/got"
  | "binary/analysis/info"
  | "binary/analysis/pattern"
  | "binary/analysis/plt"
  | "binary/analysis/rop"
  | "binary/analysis/sections"
  | "binary/analysis/symbols"
  | "cloud/asset/services"
  | "cloud/asset/takeover"
  | "cloud/asset/takeover-scan"
  | "cloud/storage/enumerate"
  | "cloud/storage/scan"
  | "code/dependencies/scan"
  | "code/secrets/providers"
  | "code/secrets/scan"
  | "code/secrets/validate"
  | "collect/browser/all"
  | "collect/browser/chrome"
  | "collect/browser/firefox"
  | "collection/screenshot/batch"
  | "collection/screenshot/capture"
  | "collection/screenshot/http"
  | "config/database/clear-password"
  | "config/database/set-password"
  | "config/database/show"
  | "config/init/create"
  | "crypto/analyze/auto"
  | "crypto/analyze/entropy"
  | "crypto/analyze/frequency"
  | "crypto/analyze/hash"
  | "crypto/cipher/crack"
  | "crypto/cipher/decrypt"
  | "crypto/cipher/encrypt"
  | "crypto/cipher/list"
  | "crypto/codec/decode"
  | "crypto/codec/detect"
  | "crypto/codec/encode"
  | "crypto/codec/list"
  | "crypto/cyclic/find"
  | "crypto/cyclic/generate"
  | "crypto/cyclic/offset"
  | "crypto/hash/verify"
  | "crypto/recipe/bake"
  | "crypto/recipe/run"
  | "crypto/vault/decrypt"
  | "crypto/vault/encrypt"
  | "crypto/vault/info"
  | "database/engine/checkpoint"
  | "database/engine/info"
  | "database/engine/open"
  | "database/engine/stats"
  | "database/query/dns"
  | "database/query/hosts"
  | "database/query/http"
  | "database/query/ports"
  | "database/query/subdomains"
  | "database/query/summary"
  | "database/query/tls"
  | "database/query/whois"
  | "database/vector/index"
  | "database/vector/info"
  | "database/vector/search"
  | "dns/record/all"
  | "dns/record/bruteforce"
  | "dns/record/describe"
  | "dns/record/email"
  | "dns/record/get"
  | "dns/record/list"
  | "dns/record/lookup"
  | "dns/record/propagation"
  | "dns/record/resolve"
  | "dns/record/reverse"
  | "dns/server/block"
  | "dns/server/hijack"
  | "dns/server/start"
  | "docs/kb/index"
  | "docs/kb/search"
  | "evasion/amsi/csharp"
  | "evasion/amsi/obfuscated"
  | "evasion/amsi/powershell"
  | "evasion/amsi/providers"
  | "evasion/antidebug/check"
  | "evasion/antidebug/paranoid"
  | "evasion/antidebug/quick"
  | "evasion/apihash/hash"
  | "evasion/apihash/list"
  | "evasion/apihash/syscalls"
  | "evasion/build/deobfuscate"
  | "evasion/build/info"
  | "evasion/build/obfuscate"
  | "evasion/build/rehash"
  | "evasion/config/aggressive"
  | "evasion/config/default"
  | "evasion/config/show"
  | "evasion/config/stealth"
  | "evasion/controlflow/demo"
  | "evasion/controlflow/predicates"
  | "evasion/controlflow/substitute"
  | "evasion/inject/encode"
  | "evasion/inject/list"
  | "evasion/inject/shellcode"
  | "evasion/memory/demo"
  | "evasion/memory/encrypt"
  | "evasion/memory/heap"
  | "evasion/memory/rotate"
  | "evasion/memory/sleep"
  | "evasion/memory/vault"
  | "evasion/network/jitter"
  | "evasion/network/shape"
  | "evasion/network/timer"
  | "evasion/obfuscate/base64"
  | "evasion/obfuscate/deobfuscate"
  | "evasion/obfuscate/rot"
  | "evasion/obfuscate/xor"
  | "evasion/sandbox/check"
  | "evasion/sandbox/delay"
  | "evasion/sandbox/score"
  | "evasion/strings/demo"
  | "evasion/strings/encrypt"
  | "evasion/strings/sensitive"
  | "evasion/tracks/clear"
  | "evasion/tracks/command"
  | "evasion/tracks/scan"
  | "evasion/tracks/sessions"
  | "exploit/browser/exec"
  | "exploit/browser/list"
  | "exploit/browser/serve"
  | "exploit/payload/apt"
  | "exploit/payload/dns-shell"
  | "exploit/payload/encrypted-shell"
  | "exploit/payload/http-shell"
  | "exploit/payload/icmp-shell"
  | "exploit/payload/lateral"
  | "exploit/payload/listener"
  | "exploit/payload/multi-shell"
  | "exploit/payload/persist"
  | "exploit/payload/plan"
  | "exploit/payload/playbooks"
  | "exploit/payload/privesc"
  | "exploit/payload/recommend"
  | "exploit/payload/replicate"
  | "exploit/payload/run"
  | "exploit/payload/sessions"
  | "exploit/payload/shell"
  | "exploit/payload/start"
  | "exploit/payload/suggest"
  | "exploit/payload/websocket-shell"
  | "exploit/phish/clone"
  | "exploit/phish/email"
  | "exploit/phish/serve"
  | "exploit/phish/templates"
  | "file/ops/hash"
  | "file/ops/info"
  | "file/ops/unzip"
  | "file/ops/zip"
  | "hex/file/compare"
  | "hex/file/info"
  | "hex/file/inspect"
  | "hex/file/read"
  | "hex/file/replace"
  | "hex/file/search"
  | "hex/file/view"
  | "hex/file/write"
  | "http/server/payloads"
  | "http/server/serve"
  | "intelligence/graph/centrality"
  | "intelligence/graph/cert"
  | "intelligence/graph/communities"
  | "intelligence/graph/components"
  | "intelligence/graph/credential"
  | "intelligence/graph/cycles"
  | "intelligence/graph/domain"
  | "intelligence/graph/export"
  | "intelligence/graph/host"
  | "intelligence/graph/import"
  | "intelligence/graph/insights"
  | "intelligence/graph/network"
  | "intelligence/graph/pagerank"
  | "intelligence/graph/paths"
  | "intelligence/graph/query"
  | "intelligence/graph/report"
  | "intelligence/graph/rql"
  | "intelligence/graph/service"
  | "intelligence/graph/stats"
  | "intelligence/graph/summary"
  | "intelligence/graph/tech"
  | "intelligence/graph/user"
  | "intelligence/graph/viz"
  | "intelligence/graph/vuln"
  | "intelligence/ioc/demo"
  | "intelligence/ioc/export"
  | "intelligence/ioc/extract"
  | "intelligence/ioc/import"
  | "intelligence/ioc/search"
  | "intelligence/ioc/types"
  | "intelligence/mitre/cache"
  | "intelligence/mitre/correlate"
  | "intelligence/mitre/coverage"
  | "intelligence/mitre/detection"
  | "intelligence/mitre/export"
  | "intelligence/mitre/gaps"
  | "intelligence/mitre/group"
  | "intelligence/mitre/map"
  | "intelligence/mitre/matrix"
  | "intelligence/mitre/mitigations"
  | "intelligence/mitre/navigator"
  | "intelligence/mitre/ports"
  | "intelligence/mitre/search"
  | "intelligence/mitre/software"
  | "intelligence/mitre/stats"
  | "intelligence/mitre/tactic"
  | "intelligence/mitre/technique"
  | "intelligence/taxii/collections"
  | "intelligence/taxii/sync"
  | "intelligence/vuln/correlate"
  | "intelligence/vuln/cpe"
  | "intelligence/vuln/cve"
  | "intelligence/vuln/exploit"
  | "intelligence/vuln/kev"
  | "intelligence/vuln/report"
  | "intelligence/vuln/scan"
  | "intelligence/vuln/search"
  | "loot/entry/add"
  | "loot/entry/delete"
  | "loot/entry/export"
  | "loot/entry/list"
  | "loot/entry/show"
  | "loot/entry/stats"
  | "loot/graph/insights"
  | "loot/graph/paths"
  | "loot/graph/rebuild"
  | "loot/graph/show"
  | "loot/graph/stats"
  | "mcp/server/start"
  | "memory/process/aob"
  | "memory/process/dump"
  | "memory/process/list"
  | "memory/process/maps"
  | "memory/process/read"
  | "memory/process/scan"
  | "memory/process/string"
  | "memory/process/write"
  | "mitm/intercept/dns"
  | "mitm/intercept/export-ca"
  | "mitm/intercept/generate-ca"
  | "mitm/intercept/proxy"
  | "mitm/intercept/shell"
  | "mitm/intercept/start"
  | "network/health/check"
  | "network/health/diff"
  | "network/health/watch"
  | "network/host/discover"
  | "network/host/fingerprint"
  | "network/host/intel"
  | "network/host/list"
  | "network/host/ping"
  | "network/nc/broker"
  | "network/nc/connect"
  | "network/nc/listen"
  | "network/nc/relay"
  | "network/nc/scan"
  | "network/ports/mass-scan"
  | "network/ports/range"
  | "network/ports/scan"
  | "network/ports/stealth"
  | "network/ports/subnet"
  | "network/ports/syn-scan"
  | "network/ports/udp-scan"
  | "network/trace/mtr"
  | "network/trace/run"
  | "password/hash/benchmark"
  | "password/hash/crack"
  | "password/hash/generate"
  | "password/hash/identify"
  | "password/hash/mask"
  | "password/hash/rules"
  | "password/hash/verify"
  | "playbook/methodology/catalog"
  | "playbook/methodology/chain"
  | "playbook/methodology/chains"
  | "playbook/methodology/history"
  | "playbook/methodology/list"
  | "playbook/methodology/phases"
  | "playbook/methodology/run"
  | "playbook/methodology/show"
  | "proxy/data/list"
  | "proxy/data/requests"
  | "proxy/data/responses"
  | "proxy/data/show"
  | "proxy/data/stats"
  | "proxy/http/start"
  | "proxy/socks5/start"
  | "proxy/transparent/iptables"
  | "proxy/transparent/nftables"
  | "proxy/transparent/start"
  | "recon/domain/asn"
  | "recon/domain/breach"
  | "recon/domain/describe"
  | "recon/domain/dnsdumpster"
  | "recon/domain/dorks"
  | "recon/domain/email"
  | "recon/domain/full"
  | "recon/domain/get"
  | "recon/domain/graph"
  | "recon/domain/harvest"
  | "recon/domain/list"
  | "recon/domain/massdns"
  | "recon/domain/osint"
  | "recon/domain/rdap"
  | "recon/domain/secrets"
  | "recon/domain/show"
  | "recon/domain/social"
  | "recon/domain/subdomains"
  | "recon/domain/urls"
  | "recon/domain/vuln"
  | "recon/domain/whois"
  | "recon/identity/breach"
  | "recon/identity/email"
  | "recon/identity/username"
  | "report/pentest/generate"
  | "report/pentest/preview"
  | "report/pentest/stats"
  | "search/data/list"
  | "search/data/query"
  | "search/data/stats"
  | "service/manage/install"
  | "service/manage/list"
  | "service/manage/restart"
  | "service/manage/start"
  | "service/manage/status"
  | "service/manage/stop"
  | "service/manage/uninstall"
  | "system/host/inspect"
  | "system/host/summary"
  | "tls/intel/fingerprint"
  | "tls/intel/infrastructure"
  | "tls/intel/scan"
  | "tls/security/audit"
  | "tls/security/ciphers"
  | "tls/security/describe"
  | "tls/security/get"
  | "tls/security/list"
  | "tls/security/mozilla"
  | "tls/security/resume"
  | "tls/security/vuln"
  | "web/asset/cert"
  | "web/asset/cms"
  | "web/asset/cms-scan"
  | "web/asset/crawl"
  | "web/asset/describe"
  | "web/asset/drupal-scan"
  | "web/asset/fingerprint"
  | "web/asset/forms"
  | "web/asset/fuzz"
  | "web/asset/get"
  | "web/asset/grade"
  | "web/asset/har-export"
  | "web/asset/har-replay"
  | "web/asset/har-to-curl"
  | "web/asset/har-view"
  | "web/asset/headers"
  | "web/asset/http2"
  | "web/asset/images"
  | "web/asset/joomla-scan"
  | "web/asset/linkfinder"
  | "web/asset/links"
  | "web/asset/list"
  | "web/asset/meta"
  | "web/asset/scan"
  | "web/asset/scrape"
  | "web/asset/security"
  | "web/asset/tables"
  | "web/asset/vuln-scan"
  | "web/asset/wpscan"
  | "web/fuzz/run"
  | "web/git/dump"
  | "web/git/scan"
  | "web/nosqli/payloads"
  | "web/nosqli/test"
  | "web/sqli/payloads"
  | "web/sqli/tampers"
  | "web/sqli/test"
  | "wordlist/collection/get"
  | "wordlist/collection/info"
  | "wordlist/collection/init"
  | "wordlist/collection/install"
  | "wordlist/collection/list"
  | "wordlist/collection/remove"
  | "wordlist/collection/search"
  | "wordlist/collection/sources"
  | "wordlist/collection/status"
  | "wordlist/collection/update"
  | "wordlist/file/filter"
  | "wordlist/file/info"
;

export type GeneratedRouteTuple =
  | ["access", "system", "file"]
  | ["access", "system", "network"]
  | ["access", "system", "process"]
  | ["access", "system", "registry"]
  | ["access", "system", "service"]
  | ["agent", "c2", "connect"]
  | ["agent", "c2", "server"]
  | ["assess", "target", "run"]
  | ["assess", "target", "show"]
  | ["attack", "target", "apt"]
  | ["attack", "target", "plan"]
  | ["attack", "target", "playbooks"]
  | ["attack", "target", "run"]
  | ["auth", "test", "http"]
  | ["bench", "load", "run"]
  | ["bench", "load", "stress"]
  | ["binary", "analysis", "checksec"]
  | ["binary", "analysis", "find"]
  | ["binary", "analysis", "got"]
  | ["binary", "analysis", "info"]
  | ["binary", "analysis", "pattern"]
  | ["binary", "analysis", "plt"]
  | ["binary", "analysis", "rop"]
  | ["binary", "analysis", "sections"]
  | ["binary", "analysis", "symbols"]
  | ["cloud", "asset", "services"]
  | ["cloud", "asset", "takeover"]
  | ["cloud", "asset", "takeover-scan"]
  | ["cloud", "storage", "enumerate"]
  | ["cloud", "storage", "scan"]
  | ["code", "dependencies", "scan"]
  | ["code", "secrets", "providers"]
  | ["code", "secrets", "scan"]
  | ["code", "secrets", "validate"]
  | ["collect", "browser", "all"]
  | ["collect", "browser", "chrome"]
  | ["collect", "browser", "firefox"]
  | ["collection", "screenshot", "batch"]
  | ["collection", "screenshot", "capture"]
  | ["collection", "screenshot", "http"]
  | ["config", "database", "clear-password"]
  | ["config", "database", "set-password"]
  | ["config", "database", "show"]
  | ["config", "init", "create"]
  | ["crypto", "analyze", "auto"]
  | ["crypto", "analyze", "entropy"]
  | ["crypto", "analyze", "frequency"]
  | ["crypto", "analyze", "hash"]
  | ["crypto", "cipher", "crack"]
  | ["crypto", "cipher", "decrypt"]
  | ["crypto", "cipher", "encrypt"]
  | ["crypto", "cipher", "list"]
  | ["crypto", "codec", "decode"]
  | ["crypto", "codec", "detect"]
  | ["crypto", "codec", "encode"]
  | ["crypto", "codec", "list"]
  | ["crypto", "cyclic", "find"]
  | ["crypto", "cyclic", "generate"]
  | ["crypto", "cyclic", "offset"]
  | ["crypto", "hash", "verify"]
  | ["crypto", "recipe", "bake"]
  | ["crypto", "recipe", "run"]
  | ["crypto", "vault", "decrypt"]
  | ["crypto", "vault", "encrypt"]
  | ["crypto", "vault", "info"]
  | ["database", "engine", "checkpoint"]
  | ["database", "engine", "info"]
  | ["database", "engine", "open"]
  | ["database", "engine", "stats"]
  | ["database", "query", "dns"]
  | ["database", "query", "hosts"]
  | ["database", "query", "http"]
  | ["database", "query", "ports"]
  | ["database", "query", "subdomains"]
  | ["database", "query", "summary"]
  | ["database", "query", "tls"]
  | ["database", "query", "whois"]
  | ["database", "vector", "index"]
  | ["database", "vector", "info"]
  | ["database", "vector", "search"]
  | ["dns", "record", "all"]
  | ["dns", "record", "bruteforce"]
  | ["dns", "record", "describe"]
  | ["dns", "record", "email"]
  | ["dns", "record", "get"]
  | ["dns", "record", "list"]
  | ["dns", "record", "lookup"]
  | ["dns", "record", "propagation"]
  | ["dns", "record", "resolve"]
  | ["dns", "record", "reverse"]
  | ["dns", "server", "block"]
  | ["dns", "server", "hijack"]
  | ["dns", "server", "start"]
  | ["docs", "kb", "index"]
  | ["docs", "kb", "search"]
  | ["evasion", "amsi", "csharp"]
  | ["evasion", "amsi", "obfuscated"]
  | ["evasion", "amsi", "powershell"]
  | ["evasion", "amsi", "providers"]
  | ["evasion", "antidebug", "check"]
  | ["evasion", "antidebug", "paranoid"]
  | ["evasion", "antidebug", "quick"]
  | ["evasion", "apihash", "hash"]
  | ["evasion", "apihash", "list"]
  | ["evasion", "apihash", "syscalls"]
  | ["evasion", "build", "deobfuscate"]
  | ["evasion", "build", "info"]
  | ["evasion", "build", "obfuscate"]
  | ["evasion", "build", "rehash"]
  | ["evasion", "config", "aggressive"]
  | ["evasion", "config", "default"]
  | ["evasion", "config", "show"]
  | ["evasion", "config", "stealth"]
  | ["evasion", "controlflow", "demo"]
  | ["evasion", "controlflow", "predicates"]
  | ["evasion", "controlflow", "substitute"]
  | ["evasion", "inject", "encode"]
  | ["evasion", "inject", "list"]
  | ["evasion", "inject", "shellcode"]
  | ["evasion", "memory", "demo"]
  | ["evasion", "memory", "encrypt"]
  | ["evasion", "memory", "heap"]
  | ["evasion", "memory", "rotate"]
  | ["evasion", "memory", "sleep"]
  | ["evasion", "memory", "vault"]
  | ["evasion", "network", "jitter"]
  | ["evasion", "network", "shape"]
  | ["evasion", "network", "timer"]
  | ["evasion", "obfuscate", "base64"]
  | ["evasion", "obfuscate", "deobfuscate"]
  | ["evasion", "obfuscate", "rot"]
  | ["evasion", "obfuscate", "xor"]
  | ["evasion", "sandbox", "check"]
  | ["evasion", "sandbox", "delay"]
  | ["evasion", "sandbox", "score"]
  | ["evasion", "strings", "demo"]
  | ["evasion", "strings", "encrypt"]
  | ["evasion", "strings", "sensitive"]
  | ["evasion", "tracks", "clear"]
  | ["evasion", "tracks", "command"]
  | ["evasion", "tracks", "scan"]
  | ["evasion", "tracks", "sessions"]
  | ["exploit", "browser", "exec"]
  | ["exploit", "browser", "list"]
  | ["exploit", "browser", "serve"]
  | ["exploit", "payload", "apt"]
  | ["exploit", "payload", "dns-shell"]
  | ["exploit", "payload", "encrypted-shell"]
  | ["exploit", "payload", "http-shell"]
  | ["exploit", "payload", "icmp-shell"]
  | ["exploit", "payload", "lateral"]
  | ["exploit", "payload", "listener"]
  | ["exploit", "payload", "multi-shell"]
  | ["exploit", "payload", "persist"]
  | ["exploit", "payload", "plan"]
  | ["exploit", "payload", "playbooks"]
  | ["exploit", "payload", "privesc"]
  | ["exploit", "payload", "recommend"]
  | ["exploit", "payload", "replicate"]
  | ["exploit", "payload", "run"]
  | ["exploit", "payload", "sessions"]
  | ["exploit", "payload", "shell"]
  | ["exploit", "payload", "start"]
  | ["exploit", "payload", "suggest"]
  | ["exploit", "payload", "websocket-shell"]
  | ["exploit", "phish", "clone"]
  | ["exploit", "phish", "email"]
  | ["exploit", "phish", "serve"]
  | ["exploit", "phish", "templates"]
  | ["file", "ops", "hash"]
  | ["file", "ops", "info"]
  | ["file", "ops", "unzip"]
  | ["file", "ops", "zip"]
  | ["hex", "file", "compare"]
  | ["hex", "file", "info"]
  | ["hex", "file", "inspect"]
  | ["hex", "file", "read"]
  | ["hex", "file", "replace"]
  | ["hex", "file", "search"]
  | ["hex", "file", "view"]
  | ["hex", "file", "write"]
  | ["http", "server", "payloads"]
  | ["http", "server", "serve"]
  | ["intelligence", "graph", "centrality"]
  | ["intelligence", "graph", "cert"]
  | ["intelligence", "graph", "communities"]
  | ["intelligence", "graph", "components"]
  | ["intelligence", "graph", "credential"]
  | ["intelligence", "graph", "cycles"]
  | ["intelligence", "graph", "domain"]
  | ["intelligence", "graph", "export"]
  | ["intelligence", "graph", "host"]
  | ["intelligence", "graph", "import"]
  | ["intelligence", "graph", "insights"]
  | ["intelligence", "graph", "network"]
  | ["intelligence", "graph", "pagerank"]
  | ["intelligence", "graph", "paths"]
  | ["intelligence", "graph", "query"]
  | ["intelligence", "graph", "report"]
  | ["intelligence", "graph", "rql"]
  | ["intelligence", "graph", "service"]
  | ["intelligence", "graph", "stats"]
  | ["intelligence", "graph", "summary"]
  | ["intelligence", "graph", "tech"]
  | ["intelligence", "graph", "user"]
  | ["intelligence", "graph", "viz"]
  | ["intelligence", "graph", "vuln"]
  | ["intelligence", "ioc", "demo"]
  | ["intelligence", "ioc", "export"]
  | ["intelligence", "ioc", "extract"]
  | ["intelligence", "ioc", "import"]
  | ["intelligence", "ioc", "search"]
  | ["intelligence", "ioc", "types"]
  | ["intelligence", "mitre", "cache"]
  | ["intelligence", "mitre", "correlate"]
  | ["intelligence", "mitre", "coverage"]
  | ["intelligence", "mitre", "detection"]
  | ["intelligence", "mitre", "export"]
  | ["intelligence", "mitre", "gaps"]
  | ["intelligence", "mitre", "group"]
  | ["intelligence", "mitre", "map"]
  | ["intelligence", "mitre", "matrix"]
  | ["intelligence", "mitre", "mitigations"]
  | ["intelligence", "mitre", "navigator"]
  | ["intelligence", "mitre", "ports"]
  | ["intelligence", "mitre", "search"]
  | ["intelligence", "mitre", "software"]
  | ["intelligence", "mitre", "stats"]
  | ["intelligence", "mitre", "tactic"]
  | ["intelligence", "mitre", "technique"]
  | ["intelligence", "taxii", "collections"]
  | ["intelligence", "taxii", "sync"]
  | ["intelligence", "vuln", "correlate"]
  | ["intelligence", "vuln", "cpe"]
  | ["intelligence", "vuln", "cve"]
  | ["intelligence", "vuln", "exploit"]
  | ["intelligence", "vuln", "kev"]
  | ["intelligence", "vuln", "report"]
  | ["intelligence", "vuln", "scan"]
  | ["intelligence", "vuln", "search"]
  | ["loot", "entry", "add"]
  | ["loot", "entry", "delete"]
  | ["loot", "entry", "export"]
  | ["loot", "entry", "list"]
  | ["loot", "entry", "show"]
  | ["loot", "entry", "stats"]
  | ["loot", "graph", "insights"]
  | ["loot", "graph", "paths"]
  | ["loot", "graph", "rebuild"]
  | ["loot", "graph", "show"]
  | ["loot", "graph", "stats"]
  | ["mcp", "server", "start"]
  | ["memory", "process", "aob"]
  | ["memory", "process", "dump"]
  | ["memory", "process", "list"]
  | ["memory", "process", "maps"]
  | ["memory", "process", "read"]
  | ["memory", "process", "scan"]
  | ["memory", "process", "string"]
  | ["memory", "process", "write"]
  | ["mitm", "intercept", "dns"]
  | ["mitm", "intercept", "export-ca"]
  | ["mitm", "intercept", "generate-ca"]
  | ["mitm", "intercept", "proxy"]
  | ["mitm", "intercept", "shell"]
  | ["mitm", "intercept", "start"]
  | ["network", "health", "check"]
  | ["network", "health", "diff"]
  | ["network", "health", "watch"]
  | ["network", "host", "discover"]
  | ["network", "host", "fingerprint"]
  | ["network", "host", "intel"]
  | ["network", "host", "list"]
  | ["network", "host", "ping"]
  | ["network", "nc", "broker"]
  | ["network", "nc", "connect"]
  | ["network", "nc", "listen"]
  | ["network", "nc", "relay"]
  | ["network", "nc", "scan"]
  | ["network", "ports", "mass-scan"]
  | ["network", "ports", "range"]
  | ["network", "ports", "scan"]
  | ["network", "ports", "stealth"]
  | ["network", "ports", "subnet"]
  | ["network", "ports", "syn-scan"]
  | ["network", "ports", "udp-scan"]
  | ["network", "trace", "mtr"]
  | ["network", "trace", "run"]
  | ["password", "hash", "benchmark"]
  | ["password", "hash", "crack"]
  | ["password", "hash", "generate"]
  | ["password", "hash", "identify"]
  | ["password", "hash", "mask"]
  | ["password", "hash", "rules"]
  | ["password", "hash", "verify"]
  | ["playbook", "methodology", "catalog"]
  | ["playbook", "methodology", "chain"]
  | ["playbook", "methodology", "chains"]
  | ["playbook", "methodology", "history"]
  | ["playbook", "methodology", "list"]
  | ["playbook", "methodology", "phases"]
  | ["playbook", "methodology", "run"]
  | ["playbook", "methodology", "show"]
  | ["proxy", "data", "list"]
  | ["proxy", "data", "requests"]
  | ["proxy", "data", "responses"]
  | ["proxy", "data", "show"]
  | ["proxy", "data", "stats"]
  | ["proxy", "http", "start"]
  | ["proxy", "socks5", "start"]
  | ["proxy", "transparent", "iptables"]
  | ["proxy", "transparent", "nftables"]
  | ["proxy", "transparent", "start"]
  | ["recon", "domain", "asn"]
  | ["recon", "domain", "breach"]
  | ["recon", "domain", "describe"]
  | ["recon", "domain", "dnsdumpster"]
  | ["recon", "domain", "dorks"]
  | ["recon", "domain", "email"]
  | ["recon", "domain", "full"]
  | ["recon", "domain", "get"]
  | ["recon", "domain", "graph"]
  | ["recon", "domain", "harvest"]
  | ["recon", "domain", "list"]
  | ["recon", "domain", "massdns"]
  | ["recon", "domain", "osint"]
  | ["recon", "domain", "rdap"]
  | ["recon", "domain", "secrets"]
  | ["recon", "domain", "show"]
  | ["recon", "domain", "social"]
  | ["recon", "domain", "subdomains"]
  | ["recon", "domain", "urls"]
  | ["recon", "domain", "vuln"]
  | ["recon", "domain", "whois"]
  | ["recon", "identity", "breach"]
  | ["recon", "identity", "email"]
  | ["recon", "identity", "username"]
  | ["report", "pentest", "generate"]
  | ["report", "pentest", "preview"]
  | ["report", "pentest", "stats"]
  | ["search", "data", "list"]
  | ["search", "data", "query"]
  | ["search", "data", "stats"]
  | ["service", "manage", "install"]
  | ["service", "manage", "list"]
  | ["service", "manage", "restart"]
  | ["service", "manage", "start"]
  | ["service", "manage", "status"]
  | ["service", "manage", "stop"]
  | ["service", "manage", "uninstall"]
  | ["system", "host", "inspect"]
  | ["system", "host", "summary"]
  | ["tls", "intel", "fingerprint"]
  | ["tls", "intel", "infrastructure"]
  | ["tls", "intel", "scan"]
  | ["tls", "security", "audit"]
  | ["tls", "security", "ciphers"]
  | ["tls", "security", "describe"]
  | ["tls", "security", "get"]
  | ["tls", "security", "list"]
  | ["tls", "security", "mozilla"]
  | ["tls", "security", "resume"]
  | ["tls", "security", "vuln"]
  | ["web", "asset", "cert"]
  | ["web", "asset", "cms"]
  | ["web", "asset", "cms-scan"]
  | ["web", "asset", "crawl"]
  | ["web", "asset", "describe"]
  | ["web", "asset", "drupal-scan"]
  | ["web", "asset", "fingerprint"]
  | ["web", "asset", "forms"]
  | ["web", "asset", "fuzz"]
  | ["web", "asset", "get"]
  | ["web", "asset", "grade"]
  | ["web", "asset", "har-export"]
  | ["web", "asset", "har-replay"]
  | ["web", "asset", "har-to-curl"]
  | ["web", "asset", "har-view"]
  | ["web", "asset", "headers"]
  | ["web", "asset", "http2"]
  | ["web", "asset", "images"]
  | ["web", "asset", "joomla-scan"]
  | ["web", "asset", "linkfinder"]
  | ["web", "asset", "links"]
  | ["web", "asset", "list"]
  | ["web", "asset", "meta"]
  | ["web", "asset", "scan"]
  | ["web", "asset", "scrape"]
  | ["web", "asset", "security"]
  | ["web", "asset", "tables"]
  | ["web", "asset", "vuln-scan"]
  | ["web", "asset", "wpscan"]
  | ["web", "fuzz", "run"]
  | ["web", "git", "dump"]
  | ["web", "git", "scan"]
  | ["web", "nosqli", "payloads"]
  | ["web", "nosqli", "test"]
  | ["web", "sqli", "payloads"]
  | ["web", "sqli", "tampers"]
  | ["web", "sqli", "test"]
  | ["wordlist", "collection", "get"]
  | ["wordlist", "collection", "info"]
  | ["wordlist", "collection", "init"]
  | ["wordlist", "collection", "install"]
  | ["wordlist", "collection", "list"]
  | ["wordlist", "collection", "remove"]
  | ["wordlist", "collection", "search"]
  | ["wordlist", "collection", "sources"]
  | ["wordlist", "collection", "status"]
  | ["wordlist", "collection", "update"]
  | ["wordlist", "file", "filter"]
  | ["wordlist", "file", "info"]
;

export interface GeneratedRouteSurface<TInvocation = unknown> {
