//! MITRE ATT&CK Navigator Layer Export
//!
//! Generates Navigator layer JSON files compatible with ATT&CK Navigator v4.x.
//! Layers can be imported into https://mitre-attack.github.io/attack-navigator/
//!
//! ## Layer Format
//!
//! Navigator layers are JSON files with:
//! - `version`: Layer format version (4.5 for current)
//! - `name`: Layer display name
//! - `domain`: ATT&CK domain (enterprise-attack, mobile-attack, ics-attack)
//! - `techniques`: Array of technique annotations (color, score, comment)
//! - `filters`: Platform/tactic filters
//! - `metadata`: Custom key-value pairs

use super::types::{AttackData, AttackMatrix};
use std::collections::HashMap;

/// Navigator layer format version
pub const LAYER_VERSION: &str = "4.5";

/// Navigator layer structure
#[derive(Debug, Clone)]
pub struct NavigatorLayer {
  /// Layer format version
  pub version: String,
  /// Layer display name
  pub name: String,
  /// Layer description
  pub description: String,
  /// ATT&CK domain
  pub domain: String,
  /// Technique annotations
  pub techniques: Vec<TechniqueAnnotation>,
  /// Gradient configuration
  pub gradient: Gradient,
  /// Legend items
  pub legend_items: Vec<LegendItem>,
  /// Custom metadata
  pub metadata: Vec<MetadataEntry>,
  /// Platform filters
  pub filters: Filters,
  /// Show sub-techniques
  pub show_subtechniques: bool,
  /// Whether to select all techniques by default
  pub select_all_techniques: bool,
  /// Sort order for techniques
  pub sorting: u8,
  /// Layout configuration
  pub layout: Layout,
  /// Hide disabled techniques
  pub hide_disabled: bool,
}

/// Technique annotation in a layer
#[derive(Debug, Clone)]
pub struct TechniqueAnnotation {
  /// Technique ID (e.g., "T1059" or "T1059.001")
  pub technique_id: String,
  /// Tactic this applies to (if technique spans multiple tactics)
  pub tactic: Option<String>,
  /// Color (hex format: "#ff0000")
  pub color: Option<String>,
  /// Numeric score (0-100)
  pub score: Option<u8>,
  /// Comment text
  pub comment: Option<String>,
  /// Whether technique is enabled (visible)
  pub enabled: bool,
  /// Whether to show sub-techniques
  pub show_subtechniques: bool,
  /// Custom metadata
  pub metadata: Vec<MetadataEntry>,
  /// Links for technique
  pub links: Vec<Link>,
}

/// Color gradient for scoring
#[derive(Debug, Clone)]
pub struct Gradient {
  /// Gradient colors (low to high)
  pub colors: Vec<String>,
  /// Min value
  pub min_value: u8,
  /// Max value
  pub max_value: u8,
}

/// Legend item
#[derive(Debug, Clone)]
pub struct LegendItem {
  /// Legend label
  pub label: String,
  /// Color (hex)
  pub color: String,
}

/// Custom metadata entry
#[derive(Debug, Clone)]
pub struct MetadataEntry {
  /// Metadata key
  pub name: String,
  /// Metadata value
  pub value: String,
}

/// Link entry
#[derive(Debug, Clone)]
pub struct Link {
  /// Link label
  pub label: String,
  /// URL
  pub url: String,
}

/// Platform and tactic filters
#[derive(Debug, Clone)]
pub struct Filters {
  /// Platform filters
  pub platforms: Vec<String>,
  /// Tactic filters
  pub tactics: Vec<String>,
}

/// Layout configuration
#[derive(Debug, Clone)]
pub struct Layout {
  /// Layout type: "side", "flat", "mini"
  pub layout_type: String,
  /// Show technique IDs
  pub show_id: bool,
  /// Show technique names
  pub show_name: bool,
  /// Show aggregate scores
  pub show_aggregate_scores: bool,
  /// Count of techniques to show
  pub count_unscored: bool,
  /// Aggregate function: "average", "min", "max", "sum"
  pub aggregate_function: String,
}

impl Default for NavigatorLayer {
  fn default() -> Self {
    Self {
      version: LAYER_VERSION.to_string(),
      name: "redblue Layer".to_string(),
      description: "Generated by redblue".to_string(),
      domain: "enterprise-attack".to_string(),
      techniques: Vec::new(),
      gradient: Gradient::default(),
      legend_items: Vec::new(),
      metadata: vec![MetadataEntry {
        name: "generator".to_string(),
        value: "redblue".to_string(),
      }],
      filters: Filters::default(),
      show_subtechniques: true,
      select_all_techniques: false,
      sorting: 0,
      layout: Layout::default(),
      hide_disabled: false,
    }
  }
}

impl Default for Gradient {
  fn default() -> Self {
    Self {
      colors: vec![
        "#ffffff".to_string(), // White (0)
        "#66b3ff".to_string(), // Light blue (25)
        "#ffff66".to_string(), // Yellow (50)
        "#ff9933".to_string(), // Orange (75)
        "#ff3333".to_string(), // Red (100)
      ],
      min_value: 0,
      max_value: 100,
    }
  }
}

impl Default for Filters {
  fn default() -> Self {
    Self {
      platforms: vec![
        "Windows".to_string(),
        "Linux".to_string(),
        "macOS".to_string(),
      ],
      tactics: Vec::new(), // Empty = all tactics
    }
  }
}

impl Default for Layout {
  fn default() -> Self {
    Self {
      layout_type: "side".to_string(),
      show_id: true,
      show_name: true,
      show_aggregate_scores: false,
      count_unscored: false,
      aggregate_function: "average".to_string(),
    }
  }
}

impl NavigatorLayer {
  /// Create a new empty layer
  pub fn new(name: &str, description: &str) -> Self {
    Self {
      name: name.to_string(),
      description: description.to_string(),
      ..Default::default()
    }
  }

  /// Set the domain based on AttackMatrix
  pub fn with_matrix(mut self, matrix: AttackMatrix) -> Self {
    self.domain = match matrix {
      AttackMatrix::Enterprise => "enterprise-attack".to_string(),
      AttackMatrix::Mobile => "mobile-attack".to_string(),
      AttackMatrix::Ics => "ics-attack".to_string(),
    };
    self
  }

  /// Add a technique annotation
  pub fn add_technique(&mut self, annotation: TechniqueAnnotation) {
    self.techniques.push(annotation);
  }

  /// Score a technique with color based on score
  pub fn score_technique(&mut self, technique_id: &str, score: u8, comment: Option<&str>) {
    let color = self.score_to_color(score);
    self.techniques.push(TechniqueAnnotation {
      technique_id: technique_id.to_string(),
      tactic: None,
      color: Some(color),
      score: Some(score),
      comment: comment.map(|s| s.to_string()),
      enabled: true,
      show_subtechniques: true,
      metadata: Vec::new(),
      links: Vec::new(),
    });
  }

  /// Convert score (0-100) to gradient color
  fn score_to_color(&self, score: u8) -> String {
    let score = score.min(100);
    let colors = &self.gradient.colors;

    if colors.is_empty() {
      return "#ffffff".to_string();
    }

    if colors.len() == 1 {
      return colors[0].clone();
    }

    // Map score to color index
    let segment_size = 100.0 / (colors.len() - 1) as f64;
    let segment_index = (score as f64 / segment_size).floor() as usize;
    let segment_index = segment_index.min(colors.len() - 2);

    // Interpolate between colors
    let segment_progress = (score as f64 - segment_index as f64 * segment_size) / segment_size;

    let color1 = &colors[segment_index];
    let color2 = &colors[segment_index + 1];

    interpolate_colors(color1, color2, segment_progress)
  }

  /// Add a legend item
  pub fn add_legend(&mut self, label: &str, color: &str) {
    self.legend_items.push(LegendItem {
      label: label.to_string(),
      color: color.to_string(),
    });
  }

  /// Set platform filters
  pub fn with_platforms(mut self, platforms: Vec<String>) -> Self {
    self.filters.platforms = platforms;
    self
  }

  /// Set tactic filters
  pub fn with_tactics(mut self, tactics: Vec<String>) -> Self {
    self.filters.tactics = tactics;
    self
  }

  /// Add custom metadata
  pub fn add_metadata(&mut self, name: &str, value: &str) {
    self.metadata.push(MetadataEntry {
      name: name.to_string(),
      value: value.to_string(),
    });
  }

  /// Export layer to JSON string
  pub fn to_json(&self) -> String {
    let mut json = String::with_capacity(4096);

    json.push_str("{\n");
    json.push_str(&format!("  \"version\": \"{}\",\n", self.version));
    json.push_str(&format!("  \"name\": \"{}\",\n", escape_json(&self.name)));
    json.push_str(&format!(
      "  \"description\": \"{}\",\n",
      escape_json(&self.description)
    ));
    json.push_str(&format!("  \"domain\": \"{}\",\n", self.domain));

    // Filters
    json.push_str("  \"filters\": {\n");
    json.push_str("    \"platforms\": [");
    json.push_str(
      &self
        .filters
        .platforms
        .iter()
        .map(|p| format!("\"{}\"", p))
        .collect::<Vec<_>>()
        .join(", "),
    );
    json.push_str("]\n");
    json.push_str("  },\n");

    // Sorting
    json.push_str(&format!("  \"sorting\": {},\n", self.sorting));

    // Layout
    json.push_str("  \"layout\": {\n");
    json.push_str(&format!(
      "    \"layout\": \"{}\",\n",
      self.layout.layout_type
    ));
    json.push_str(&format!(
      "    \"showID\": {},\n",
      if self.layout.show_id { "true" } else { "false" }
    ));
    json.push_str(&format!(
      "    \"showName\": {},\n",
      if self.layout.show_name {
        "true"
      } else {
        "false"
      }
    ));
    json.push_str(&format!(
      "    \"showAggregateScores\": {},\n",
      if self.layout.show_aggregate_scores {
        "true"
      } else {
        "false"
      }
    ));
    json.push_str(&format!(
      "    \"countUnscored\": {},\n",
      if self.layout.count_unscored {
        "true"
      } else {
        "false"
      }
    ));
    json.push_str(&format!(
      "    \"aggregateFunction\": \"{}\"\n",
      self.layout.aggregate_function
    ));
    json.push_str("  },\n");

    // Hide disabled
    json.push_str(&format!(
      "  \"hideDisabled\": {},\n",
      if self.hide_disabled { "true" } else { "false" }
    ));

    // Gradient
    json.push_str("  \"gradient\": {\n");
    json.push_str("    \"colors\": [");
    json.push_str(
      &self
        .gradient
        .colors
        .iter()
        .map(|c| format!("\"{}\"", c))
        .collect::<Vec<_>>()
        .join(", "),
    );
    json.push_str("],\n");
    json.push_str(&format!("    \"minValue\": {},\n", self.gradient.min_value));
    json.push_str(&format!("    \"maxValue\": {}\n", self.gradient.max_value));
    json.push_str("  },\n");

    // Legend items
    json.push_str("  \"legendItems\": [");
    if !self.legend_items.is_empty() {
      json.push('\n');
      for (i, item) in self.legend_items.iter().enumerate() {
        json.push_str(&format!(
          "    {{\"label\": \"{}\", \"color\": \"{}\"}}",
          escape_json(&item.label),
          item.color
        ));
        if i < self.legend_items.len() - 1 {
          json.push(',');
        }
        json.push('\n');
      }
      json.push_str("  ");
    }
    json.push_str("],\n");

    // Metadata
    json.push_str("  \"metadata\": [");
    if !self.metadata.is_empty() {
      json.push('\n');
      for (i, entry) in self.metadata.iter().enumerate() {
        json.push_str(&format!(
          "    {{\"name\": \"{}\", \"value\": \"{}\"}}",
          escape_json(&entry.name),
          escape_json(&entry.value)
        ));
        if i < self.metadata.len() - 1 {
          json.push(',');
        }
        json.push('\n');
      }
      json.push_str("  ");
    }
    json.push_str("],\n");

    // Show subtechniques
    json.push_str(&format!("  \"showTacticRowBackground\": true,\n"));
    json.push_str(&format!("  \"tacticRowBackground\": \"#dddddd\",\n"));
    json.push_str(&format!("  \"selectTechniquesAcrossTactics\": true,\n"));
    json.push_str(&format!("  \"selectSubtechniquesWithParent\": false,\n"));

    // Techniques
    json.push_str("  \"techniques\": [");
    if !self.techniques.is_empty() {
      json.push('\n');
      for (i, tech) in self.techniques.iter().enumerate() {
        json.push_str("    {\n");
        json.push_str(&format!("      \"techniqueID\": \"{}\"", tech.technique_id));

        if let Some(ref tactic) = tech.tactic {
          json.push_str(&format!(",\n      \"tactic\": \"{}\"", tactic));
        }

        if let Some(ref color) = tech.color {
          json.push_str(&format!(",\n      \"color\": \"{}\"", color));
        }

        if let Some(score) = tech.score {
          json.push_str(&format!(",\n      \"score\": {}", score));
        }

        if let Some(ref comment) = tech.comment {
          json.push_str(&format!(
            ",\n      \"comment\": \"{}\"",
            escape_json(comment)
          ));
        }

        json.push_str(&format!(
          ",\n      \"enabled\": {}",
          if tech.enabled { "true" } else { "false" }
        ));

        json.push_str(&format!(
          ",\n      \"showSubtechniques\": {}",
          if tech.show_subtechniques {
            "true"
          } else {
            "false"
          }
        ));

        // Metadata
        if !tech.metadata.is_empty() {
          json.push_str(",\n      \"metadata\": [");
          for (j, entry) in tech.metadata.iter().enumerate() {
            json.push_str(&format!(
              "{{\"name\": \"{}\", \"value\": \"{}\"}}",
              escape_json(&entry.name),
              escape_json(&entry.value)
            ));
            if j < tech.metadata.len() - 1 {
              json.push_str(", ");
            }
          }
          json.push(']');
        }

        // Links
        if !tech.links.is_empty() {
          json.push_str(",\n      \"links\": [");
          for (j, link) in tech.links.iter().enumerate() {
            json.push_str(&format!(
              "{{\"label\": \"{}\", \"url\": \"{}\"}}",
              escape_json(&link.label),
              escape_json(&link.url)
            ));
            if j < tech.links.len() - 1 {
              json.push_str(", ");
            }
          }
          json.push(']');
        }

        json.push_str("\n    }");
        if i < self.techniques.len() - 1 {
          json.push(',');
        }
        json.push('\n');
      }
      json.push_str("  ");
    }
    json.push_str("]\n");

    json.push('}');

    json
  }
}

/// Layer builder for convenient creation
pub struct LayerBuilder {
  layer: NavigatorLayer,
  technique_scores: HashMap<String, (u8, Option<String>)>,
}

impl LayerBuilder {
  /// Create a new layer builder
  pub fn new(name: &str) -> Self {
    Self {
      layer: NavigatorLayer::new(name, ""),
      technique_scores: HashMap::new(),
    }
  }

  /// Set layer description
  pub fn description(mut self, desc: &str) -> Self {
    self.layer.description = desc.to_string();
    self
  }

  /// Set domain
  pub fn matrix(mut self, matrix: AttackMatrix) -> Self {
    self.layer = self.layer.with_matrix(matrix);
    self
  }

  /// Score a technique
  pub fn score(mut self, technique_id: &str, score: u8) -> Self {
    self
      .technique_scores
      .insert(technique_id.to_string(), (score, None));
    self
  }

  /// Score a technique with comment
  pub fn score_with_comment(mut self, technique_id: &str, score: u8, comment: &str) -> Self {
    self
      .technique_scores
      .insert(technique_id.to_string(), (score, Some(comment.to_string())));
    self
  }

  /// Add a legend
  pub fn legend(mut self, label: &str, color: &str) -> Self {
    self.layer.add_legend(label, color);
    self
  }

  /// Build the layer
  pub fn build(mut self) -> NavigatorLayer {
    for (technique_id, (score, comment)) in self.technique_scores {
      self
        .layer
        .score_technique(&technique_id, score, comment.as_deref());
    }
    self.layer
  }
}

/// Create a layer from a list of technique IDs (all scored equally)
pub fn layer_from_techniques(
  name: &str,
  description: &str,
  techniques: &[&str],
  score: u8,
) -> NavigatorLayer {
  let mut layer = NavigatorLayer::new(name, description);

  for tech_id in techniques {
    layer.score_technique(tech_id, score, None);
  }

  layer
}

/// Create a layer from AttackData showing coverage of techniques by a group
pub fn layer_from_group(
  attack_data: &AttackData,
  group_id: &str,
  score: u8,
) -> Option<NavigatorLayer> {
  let group = attack_data.get_group(group_id)?;

  let mut layer = NavigatorLayer::new(
    &format!("{} Techniques", group.name),
    &format!("Techniques used by {} ({})", group.name, group.id),
  );

  // Add techniques used by the group
  for tech_id in &group.techniques {
    if let Some(tech) = attack_data.get_technique(tech_id) {
      layer.score_technique(&tech.id, score, Some(&tech.name));
    }
  }

  layer.add_legend(
    &format!("{} uses", group.name),
    &layer.score_to_color(score),
  );

  Some(layer)
}

/// Create a layer showing technique coverage across multiple groups
pub fn layer_from_groups(
  attack_data: &AttackData,
  group_ids: &[&str],
  name: &str,
) -> NavigatorLayer {
  let mut technique_counts: HashMap<String, usize> = HashMap::new();

  // Count techniques across groups
  for group_id in group_ids {
    if let Some(group) = attack_data.get_group(group_id) {
      for tech_id in &group.techniques {
        *technique_counts.entry(tech_id.clone()).or_insert(0) += 1;
      }
    }
  }

  let mut layer = NavigatorLayer::new(name, &format!("Coverage across {} groups", group_ids.len()));

  // Score based on how many groups use each technique
  let max_count = group_ids.len();
  for (tech_id, count) in technique_counts {
    let score = ((count as f64 / max_count as f64) * 100.0) as u8;
    layer.score_technique(
      &tech_id,
      score,
      Some(&format!("Used by {}/{} groups", count, max_count)),
    );
  }

  layer
}

/// Create a layer for a specific tactic
pub fn layer_from_tactic(
  attack_data: &AttackData,
  tactic_id: &str,
  score: u8,
) -> Option<NavigatorLayer> {
  let tactic = attack_data.get_tactic(tactic_id)?;

  let mut layer = NavigatorLayer::new(
    &format!("{} Techniques", tactic.name),
    &format!("All techniques for tactic: {}", tactic.name),
  );

  // Add all techniques for this tactic
  let techniques = attack_data.techniques_for_tactic(tactic_id);
  for tech in techniques {
    layer.score_technique(&tech.id, score, None);
  }

  Some(layer)
}

// Helper functions

/// Escape JSON special characters
fn escape_json(s: &str) -> String {
  let mut result = String::with_capacity(s.len());
  for c in s.chars() {
    match c {
      '"' => result.push_str("\\\""),
      '\\' => result.push_str("\\\\"),
      '\n' => result.push_str("\\n"),
      '\r' => result.push_str("\\r"),
      '\t' => result.push_str("\\t"),
      c => result.push(c),
    }
  }
  result
}

/// Interpolate between two hex colors
fn interpolate_colors(color1: &str, color2: &str, t: f64) -> String {
  let c1 = parse_hex_color(color1);
  let c2 = parse_hex_color(color2);

  let r = (c1.0 as f64 + (c2.0 as f64 - c1.0 as f64) * t).round() as u8;
  let g = (c1.1 as f64 + (c2.1 as f64 - c1.1 as f64) * t).round() as u8;
  let b = (c1.2 as f64 + (c2.2 as f64 - c1.2 as f64) * t).round() as u8;

  format!("#{:02x}{:02x}{:02x}", r, g, b)
}

/// Parse hex color to RGB tuple
fn parse_hex_color(hex: &str) -> (u8, u8, u8) {
  let hex = hex.trim_start_matches('#');
  if hex.len() != 6 {
    return (255, 255, 255);
  }

  let r = u8::from_str_radix(&hex[0..2], 16).unwrap_or(255);
  let g = u8::from_str_radix(&hex[2..4], 16).unwrap_or(255);
  let b = u8::from_str_radix(&hex[4..6], 16).unwrap_or(255);

  (r, g, b)
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn test_layer_creation() {
    let layer = NavigatorLayer::new("Test Layer", "Test description");
    assert_eq!(layer.name, "Test Layer");
    assert_eq!(layer.version, "4.5");
    assert_eq!(layer.domain, "enterprise-attack");
  }

  #[test]
  fn test_score_technique() {
    let mut layer = NavigatorLayer::new("Test", "Test");
    layer.score_technique("T1059", 75, Some("PowerShell"));

    assert_eq!(layer.techniques.len(), 1);
    assert_eq!(layer.techniques[0].technique_id, "T1059");
    assert_eq!(layer.techniques[0].score, Some(75));
  }

  #[test]
  fn test_score_to_color() {
    let layer = NavigatorLayer::default();

    // Test boundary colors
    let color_0 = layer.score_to_color(0);
    let color_100 = layer.score_to_color(100);

    assert!(color_0.starts_with('#'));
    assert!(color_100.starts_with('#'));
  }

  #[test]
  fn test_layer_builder() {
    let layer = LayerBuilder::new("Test Layer")
      .description("Built with builder")
      .score("T1059", 80)
      .score_with_comment("T1055", 60, "Process injection")
      .build();

    assert_eq!(layer.techniques.len(), 2);
  }

  #[test]
  fn test_layer_to_json() {
    let mut layer = NavigatorLayer::new("Test", "Testing JSON output");
    layer.score_technique("T1059", 75, Some("Test comment"));

    let json = layer.to_json();
    assert!(json.contains("\"version\": \"4.5\""));
    assert!(json.contains("\"name\": \"Test\""));
    assert!(json.contains("\"techniqueID\": \"T1059\""));
    assert!(json.contains("\"score\": 75"));
  }

  #[test]
  fn test_escape_json() {
    assert_eq!(escape_json("hello"), "hello");
    assert_eq!(escape_json("hello\"world"), "hello\\\"world");
    assert_eq!(escape_json("line1\nline2"), "line1\\nline2");
  }

  #[test]
  fn test_interpolate_colors() {
    let result = interpolate_colors("#000000", "#ffffff", 0.5);
    assert_eq!(result, "#808080"); // Middle gray

    let result = interpolate_colors("#ff0000", "#0000ff", 0.5);
    assert_eq!(result, "#800080"); // Purple
  }

  #[test]
  fn test_layer_from_techniques() {
    let layer = layer_from_techniques(
      "Coverage",
      "Detected techniques",
      &["T1059", "T1055", "T1003"],
      80,
    );

    assert_eq!(layer.techniques.len(), 3);
  }
}
