//! DevOps & CI/CD Secret Patterns
//!
//! Patterns for GitHub, GitLab, CI/CD systems, Docker, Kubernetes, Terraform, etc.

use super::super::SecretSeverity;
use super::types::{PatternCategory, PatternMatcher, SecretPattern};

/// Get all DevOps patterns
pub fn patterns() -> Vec<SecretPattern> {
    vec![
        // ===============================
        // GitHub
        // ===============================
        SecretPattern {
            name: "GitHub Personal Access Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::Prefix("ghp_"),
            severity: SecretSeverity::Critical,
            keywords: vec!["github", "token", "pat"],
            requires_entropy: false,
            min_length: 40,
            max_length: 50,
            description: "GitHub Personal Access Token (new format)",
        },
        SecretPattern {
            name: "GitHub OAuth Access Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::Prefix("gho_"),
            severity: SecretSeverity::High,
            keywords: vec!["github", "oauth", "token"],
            requires_entropy: false,
            min_length: 40,
            max_length: 50,
            description: "GitHub OAuth Access Token",
        },
        SecretPattern {
            name: "GitHub App Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::Any(vec![
                PatternMatcher::Prefix("ghu_"),
                PatternMatcher::Prefix("ghs_"),
            ]),
            severity: SecretSeverity::High,
            keywords: vec!["github", "app", "token"],
            requires_entropy: false,
            min_length: 40,
            max_length: 50,
            description: "GitHub App Token",
        },
        SecretPattern {
            name: "GitHub Refresh Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::Prefix("ghr_"),
            severity: SecretSeverity::High,
            keywords: vec!["github", "refresh", "token"],
            requires_entropy: false,
            min_length: 40,
            max_length: 80,
            description: "GitHub Refresh Token",
        },
        // ===============================
        // GitLab
        // ===============================
        SecretPattern {
            name: "GitLab Personal Access Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::Prefix("glpat-"),
            severity: SecretSeverity::Critical,
            keywords: vec!["gitlab", "token", "pat"],
            requires_entropy: false,
            min_length: 26,
            max_length: 30,
            description: "GitLab Personal Access Token",
        },
        SecretPattern {
            name: "GitLab Pipeline Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::Prefix("glptt-"),
            severity: SecretSeverity::High,
            keywords: vec!["gitlab", "pipeline", "token"],
            requires_entropy: false,
            min_length: 26,
            max_length: 70,
            description: "GitLab Pipeline Trigger Token",
        },
        // ===============================
        // CI/CD Systems
        // ===============================
        SecretPattern {
            name: "CircleCI API Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::HexLength(40),
            severity: SecretSeverity::High,
            keywords: vec!["circleci", "circle", "token", "api"],
            requires_entropy: true,
            min_length: 40,
            max_length: 40,
            description: "CircleCI Personal API Token",
        },
        SecretPattern {
            name: "Travis CI API Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::CharsetRange {
                charset: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-",
                min_len: 22,
                max_len: 32,
            },
            severity: SecretSeverity::High,
            keywords: vec!["travis", "travis-ci", "token", "api"],
            requires_entropy: true,
            min_length: 22,
            max_length: 32,
            description: "Travis CI API Token",
        },
        SecretPattern {
            name: "Jenkins API Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::HexLength(32),
            severity: SecretSeverity::High,
            keywords: vec!["jenkins", "token", "api"],
            requires_entropy: true,
            min_length: 32,
            max_length: 34,
            description: "Jenkins API Token",
        },
        SecretPattern {
            name: "Buildkite API Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::Prefix("bkua_"),
            severity: SecretSeverity::High,
            keywords: vec!["buildkite", "bk", "token", "api"],
            requires_entropy: false,
            min_length: 40,
            max_length: 50,
            description: "Buildkite Agent Token",
        },
        SecretPattern {
            name: "Bitbucket App Password",
            category: PatternCategory::Password,
            pattern: PatternMatcher::CharsetRange {
                charset: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",
                min_len: 20,
                max_len: 24,
            },
            severity: SecretSeverity::High,
            keywords: vec!["bitbucket", "app", "password", "token"],
            requires_entropy: true,
            min_length: 20,
            max_length: 24,
            description: "Bitbucket App Password",
        },
        SecretPattern {
            name: "Drone CI Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::CharsetRange {
                charset: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",
                min_len: 32,
                max_len: 40,
            },
            severity: SecretSeverity::High,
            keywords: vec!["drone", "ci", "token"],
            requires_entropy: true,
            min_length: 32,
            max_length: 40,
            description: "Drone CI Access Token",
        },
        // ===============================
        // Infrastructure
        // ===============================
        SecretPattern {
            name: "Kubernetes Service Account Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::Contains("eyJhbGciOiJSUzI1NiI"),
            severity: SecretSeverity::Critical,
            keywords: vec!["kubernetes", "k8s", "service", "account", "token"],
            requires_entropy: false,
            min_length: 100,
            max_length: 2000,
            description: "Kubernetes Service Account Token",
        },
        SecretPattern {
            name: "Docker Hub Access Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::Prefix("dckr_pat_"),
            severity: SecretSeverity::High,
            keywords: vec!["docker", "hub", "token", "registry"],
            requires_entropy: false,
            min_length: 36,
            max_length: 50,
            description: "Docker Hub Personal Access Token",
        },
        SecretPattern {
            name: "Terraform Cloud API Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::CharsetRange {
                charset: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.",
                min_len: 80,
                max_len: 100,
            },
            severity: SecretSeverity::Critical,
            keywords: vec!["terraform", "cloud", "api", "token"],
            requires_entropy: true,
            min_length: 80,
            max_length: 100,
            description: "Terraform Cloud API Token",
        },
        SecretPattern {
            name: "HashiCorp Vault Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::Prefix("hvs."),
            severity: SecretSeverity::Critical,
            keywords: vec!["vault", "hashicorp", "token"],
            requires_entropy: false,
            min_length: 20,
            max_length: 200,
            description: "HashiCorp Vault Service Token",
        },
        SecretPattern {
            name: "Pulumi Access Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::Prefix("pul-"),
            severity: SecretSeverity::High,
            keywords: vec!["pulumi", "access", "token"],
            requires_entropy: false,
            min_length: 36,
            max_length: 50,
            description: "Pulumi Access Token",
        },
        // ===============================
        // Deployment Platforms
        // ===============================
        SecretPattern {
            name: "Vercel Access Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::Prefix("vercel_"),
            severity: SecretSeverity::High,
            keywords: vec!["vercel", "token", "deployment"],
            requires_entropy: false,
            min_length: 20,
            max_length: 30,
            description: "Vercel Access Token",
        },
        SecretPattern {
            name: "Netlify Access Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::CharsetRange {
                charset: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-",
                min_len: 40,
                max_len: 60,
            },
            severity: SecretSeverity::High,
            keywords: vec!["netlify", "token", "access"],
            requires_entropy: true,
            min_length: 40,
            max_length: 60,
            description: "Netlify Personal Access Token",
        },
        SecretPattern {
            name: "Render API Key",
            category: PatternCategory::ApiKey,
            pattern: PatternMatcher::Prefix("rnd_"),
            severity: SecretSeverity::High,
            keywords: vec!["render", "api", "key"],
            requires_entropy: false,
            min_length: 30,
            max_length: 50,
            description: "Render API Key",
        },
        SecretPattern {
            name: "Railway API Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::CharsetRange {
                charset: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-",
                min_len: 36,
                max_len: 50,
            },
            severity: SecretSeverity::High,
            keywords: vec!["railway", "api", "token"],
            requires_entropy: true,
            min_length: 36,
            max_length: 50,
            description: "Railway API Token",
        },
        SecretPattern {
            name: "Expo Access Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::CharsetRange {
                charset: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-",
                min_len: 40,
                max_len: 60,
            },
            severity: SecretSeverity::High,
            keywords: vec!["expo", "access", "token"],
            requires_entropy: true,
            min_length: 40,
            max_length: 60,
            description: "Expo Access Token",
        },
        // ===============================
        // Secrets Management
        // ===============================
        SecretPattern {
            name: "1Password Connect Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::Prefix("ops_"),
            severity: SecretSeverity::Critical,
            keywords: vec!["1password", "connect", "token"],
            requires_entropy: false,
            min_length: 100,
            max_length: 200,
            description: "1Password Connect Server Token",
        },
        SecretPattern {
            name: "Doppler Service Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::Prefix("dp.st."),
            severity: SecretSeverity::Critical,
            keywords: vec!["doppler", "service", "token"],
            requires_entropy: false,
            min_length: 40,
            max_length: 60,
            description: "Doppler Service Token",
        },
        SecretPattern {
            name: "Infisical Token",
            category: PatternCategory::Token,
            pattern: PatternMatcher::Prefix("st."),
            severity: SecretSeverity::Critical,
            keywords: vec!["infisical", "service", "token"],
            requires_entropy: false,
            min_length: 80,
            max_length: 150,
            description: "Infisical Service Token",
        },
    ]
}
