#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
BASELINE_PATH = ROOT / "scripts" / "machine-output-baseline.txt"
COMMANDS_DIR = ROOT / "src" / "cli" / "commands"

# Detect hand-built JSON written directly with print macros.
PATTERNS = (
    'println!("{{"',
    'print!("{{"',
    'println!("{{{',
    'print!("{{{',
)


def scan_offenders() -> list[str]:
    offenders: list[str] = []
    for path in sorted(COMMANDS_DIR.rglob("*.rs")):
        text = path.read_text(encoding="utf-8", errors="ignore")
        if any(pattern in text for pattern in PATTERNS):
            offenders.append(path.relative_to(ROOT).as_posix())
    return offenders


def read_baseline(path: Path) -> set[str]:
    if not path.exists():
        return set()
    lines = [line.strip() for line in path.read_text(encoding="utf-8").splitlines()]
    return {line for line in lines if line and not line.startswith("#")}


def write_baseline(path: Path, offenders: list[str]) -> None:
    header = [
        "# Files that still hand-build JSON with println!/print! in CLI commands.",
        "# Keep this list shrinking over time.",
        "# Generated by scripts/check-machine-output.py --update-baseline",
        "",
    ]
    path.write_text("\n".join(header + offenders) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Guardrail for machine-readable CLI output regressions."
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Fail if any direct JSON print offenders remain.",
    )
    parser.add_argument(
        "--update-baseline",
        action="store_true",
        help="Rewrite the baseline file from the current offender set.",
    )
    args = parser.parse_args()

    offenders = scan_offenders()

    if args.update_baseline:
        write_baseline(BASELINE_PATH, offenders)
        print(f"Updated baseline with {len(offenders)} offenders: {BASELINE_PATH}")
        return 0

    if args.strict:
        if offenders:
            print("Machine-output strict mode failed. Offenders:")
            for offender in offenders:
                print(f"  - {offender}")
            return 1
        print("Machine-output strict mode passed. No direct JSON print offenders found.")
        return 0

    baseline = read_baseline(BASELINE_PATH)
    current = set(offenders)

    new_offenders = sorted(current - baseline)
    fixed_files = sorted(baseline - current)

    print(f"Machine-output audit: {len(offenders)} current offender files")
    if fixed_files:
        print("Files removed from offender set since baseline:")
        for fixed in fixed_files:
            print(f"  - {fixed}")

    if new_offenders:
        print("New offender files detected:")
        for offender in new_offenders:
            print(f"  - {offender}")
        print(
            "\nFailing because new direct JSON print patterns were introduced.\n"
            "Migrate the command to Output::json_value / Output::json or update the baseline intentionally."
        )
        return 1

    print("No new machine-output regressions detected against baseline.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
