// @generated by scripts/generate-sdk-surface.js
// Manifest-driven route typing contract. Do not edit manually.

export type GeneratedCanonicalRoutePath =
  | "access/system/file"
  | "access/system/network"
  | "access/system/process"
  | "access/system/registry"
  | "access/system/service"
  | "agent/c2/connect"
  | "agent/c2/server"
  | "assess/target/run"
  | "assess/target/show"
  | "attack/target/apt"
  | "attack/target/plan"
  | "attack/target/playbooks"
  | "attack/target/run"
  | "auth/test/http"
  | "bench/load/run"
  | "bench/load/stress"
  | "binary/analysis/checksec"
  | "binary/analysis/find"
  | "binary/analysis/got"
  | "binary/analysis/info"
  | "binary/analysis/pattern"
  | "binary/analysis/plt"
  | "binary/analysis/rop"
  | "binary/analysis/sections"
  | "binary/analysis/symbols"
  | "cloud/asset/services"
  | "cloud/asset/takeover"
  | "cloud/asset/takeover-scan"
  | "cloud/storage/enumerate"
  | "cloud/storage/scan"
  | "code/dependencies/scan"
  | "code/secrets/providers"
  | "code/secrets/scan"
  | "code/secrets/validate"
  | "collect/browser/all"
  | "collect/browser/chrome"
  | "collect/browser/firefox"
  | "collection/screenshot/batch"
  | "collection/screenshot/capture"
  | "collection/screenshot/http"
  | "config/database/clear-password"
  | "config/database/set-password"
  | "config/database/show"
  | "config/init/create"
  | "crypto/analyze/auto"
  | "crypto/analyze/entropy"
  | "crypto/analyze/frequency"
  | "crypto/analyze/hash"
  | "crypto/cipher/crack"
  | "crypto/cipher/decrypt"
  | "crypto/cipher/encrypt"
  | "crypto/cipher/list"
  | "crypto/codec/decode"
  | "crypto/codec/detect"
  | "crypto/codec/encode"
  | "crypto/codec/list"
  | "crypto/cyclic/find"
  | "crypto/cyclic/generate"
  | "crypto/cyclic/offset"
  | "crypto/hash/verify"
  | "crypto/recipe/bake"
  | "crypto/recipe/run"
  | "crypto/vault/decrypt"
  | "crypto/vault/encrypt"
  | "crypto/vault/info"
  | "database/engine/checkpoint"
  | "database/engine/info"
  | "database/engine/open"
  | "database/engine/stats"
  | "database/query/dns"
  | "database/query/hosts"
  | "database/query/http"
  | "database/query/ports"
  | "database/query/subdomains"
  | "database/query/summary"
  | "database/query/tls"
  | "database/query/whois"
  | "database/vector/index"
  | "database/vector/info"
  | "database/vector/search"
  | "dns/record/all"
  | "dns/record/bruteforce"
  | "dns/record/describe"
  | "dns/record/email"
  | "dns/record/get"
  | "dns/record/list"
  | "dns/record/lookup"
  | "dns/record/propagation"
  | "dns/record/resolve"
  | "dns/record/reverse"
  | "dns/server/block"
  | "dns/server/hijack"
  | "dns/server/start"
  | "docs/kb/index"
  | "docs/kb/search"
  | "evasion/amsi/csharp"
  | "evasion/amsi/obfuscated"
  | "evasion/amsi/powershell"
  | "evasion/amsi/providers"
  | "evasion/antidebug/check"
  | "evasion/antidebug/paranoid"
  | "evasion/antidebug/quick"
  | "evasion/apihash/hash"
  | "evasion/apihash/list"
  | "evasion/apihash/syscalls"
  | "evasion/build/deobfuscate"
  | "evasion/build/info"
  | "evasion/build/obfuscate"
  | "evasion/build/rehash"
  | "evasion/config/aggressive"
  | "evasion/config/default"
  | "evasion/config/show"
  | "evasion/config/stealth"
  | "evasion/controlflow/demo"
  | "evasion/controlflow/predicates"
  | "evasion/controlflow/substitute"
  | "evasion/inject/encode"
  | "evasion/inject/list"
  | "evasion/inject/shellcode"
  | "evasion/memory/demo"
  | "evasion/memory/encrypt"
  | "evasion/memory/heap"
  | "evasion/memory/rotate"
  | "evasion/memory/sleep"
  | "evasion/memory/vault"
  | "evasion/network/jitter"
  | "evasion/network/shape"
  | "evasion/network/timer"
  | "evasion/obfuscate/base64"
  | "evasion/obfuscate/deobfuscate"
  | "evasion/obfuscate/rot"
  | "evasion/obfuscate/xor"
  | "evasion/sandbox/check"
  | "evasion/sandbox/delay"
  | "evasion/sandbox/score"
  | "evasion/strings/demo"
  | "evasion/strings/encrypt"
  | "evasion/strings/sensitive"
  | "evasion/tracks/clear"
  | "evasion/tracks/command"
  | "evasion/tracks/scan"
  | "evasion/tracks/sessions"
  | "exploit/browser/exec"
  | "exploit/browser/list"
  | "exploit/browser/serve"
  | "exploit/payload/apt"
  | "exploit/payload/dns-shell"
  | "exploit/payload/encrypted-shell"
  | "exploit/payload/http-shell"
  | "exploit/payload/icmp-shell"
  | "exploit/payload/lateral"
  | "exploit/payload/listener"
  | "exploit/payload/multi-shell"
  | "exploit/payload/persist"
  | "exploit/payload/plan"
  | "exploit/payload/playbooks"
  | "exploit/payload/privesc"
  | "exploit/payload/recommend"
  | "exploit/payload/replicate"
  | "exploit/payload/run"
  | "exploit/payload/sessions"
  | "exploit/payload/shell"
  | "exploit/payload/start"
  | "exploit/payload/suggest"
  | "exploit/payload/websocket-shell"
  | "exploit/phish/clone"
  | "exploit/phish/email"
  | "exploit/phish/serve"
  | "exploit/phish/templates"
  | "file/ops/hash"
  | "file/ops/info"
  | "file/ops/unzip"
  | "file/ops/zip"
  | "hex/file/compare"
  | "hex/file/info"
  | "hex/file/inspect"
  | "hex/file/read"
  | "hex/file/replace"
  | "hex/file/search"
  | "hex/file/view"
  | "hex/file/write"
  | "http/server/payloads"
  | "http/server/serve"
  | "intelligence/graph/centrality"
  | "intelligence/graph/cert"
  | "intelligence/graph/communities"
  | "intelligence/graph/components"
  | "intelligence/graph/credential"
  | "intelligence/graph/cycles"
  | "intelligence/graph/domain"
  | "intelligence/graph/export"
  | "intelligence/graph/host"
  | "intelligence/graph/import"
  | "intelligence/graph/insights"
  | "intelligence/graph/network"
  | "intelligence/graph/pagerank"
  | "intelligence/graph/paths"
  | "intelligence/graph/query"
  | "intelligence/graph/report"
  | "intelligence/graph/rql"
  | "intelligence/graph/service"
  | "intelligence/graph/stats"
  | "intelligence/graph/summary"
  | "intelligence/graph/tech"
  | "intelligence/graph/user"
  | "intelligence/graph/viz"
  | "intelligence/graph/vuln"
  | "intelligence/ioc/demo"
  | "intelligence/ioc/export"
  | "intelligence/ioc/extract"
  | "intelligence/ioc/import"
  | "intelligence/ioc/search"
  | "intelligence/ioc/types"
  | "intelligence/mitre/cache"
  | "intelligence/mitre/correlate"
  | "intelligence/mitre/coverage"
  | "intelligence/mitre/detection"
  | "intelligence/mitre/export"
  | "intelligence/mitre/gaps"
  | "intelligence/mitre/group"
  | "intelligence/mitre/map"
  | "intelligence/mitre/matrix"
  | "intelligence/mitre/mitigations"
  | "intelligence/mitre/navigator"
  | "intelligence/mitre/ports"
  | "intelligence/mitre/search"
  | "intelligence/mitre/software"
  | "intelligence/mitre/stats"
  | "intelligence/mitre/tactic"
  | "intelligence/mitre/technique"
  | "intelligence/taxii/collections"
  | "intelligence/taxii/sync"
  | "intelligence/vuln/correlate"
  | "intelligence/vuln/cpe"
  | "intelligence/vuln/cve"
  | "intelligence/vuln/exploit"
  | "intelligence/vuln/kev"
  | "intelligence/vuln/report"
  | "intelligence/vuln/scan"
  | "intelligence/vuln/search"
  | "loot/entry/add"
  | "loot/entry/delete"
  | "loot/entry/export"
  | "loot/entry/list"
  | "loot/entry/show"
  | "loot/entry/stats"
  | "loot/graph/insights"
  | "loot/graph/paths"
  | "loot/graph/rebuild"
  | "loot/graph/show"
  | "loot/graph/stats"
  | "mcp/server/start"
  | "memory/process/aob"
  | "memory/process/dump"
  | "memory/process/list"
  | "memory/process/maps"
  | "memory/process/read"
  | "memory/process/scan"
  | "memory/process/string"
  | "memory/process/write"
  | "mitm/intercept/dns"
  | "mitm/intercept/export-ca"
  | "mitm/intercept/generate-ca"
  | "mitm/intercept/proxy"
  | "mitm/intercept/shell"
  | "mitm/intercept/start"
  | "network/health/check"
  | "network/health/diff"
  | "network/health/watch"
  | "network/host/discover"
  | "network/host/fingerprint"
  | "network/host/intel"
  | "network/host/list"
  | "network/host/ping"
  | "network/nc/broker"
  | "network/nc/connect"
  | "network/nc/listen"
  | "network/nc/relay"
  | "network/nc/scan"
  | "network/ports/mass-scan"
  | "network/ports/range"
  | "network/ports/scan"
  | "network/ports/stealth"
  | "network/ports/subnet"
  | "network/ports/syn-scan"
  | "network/ports/udp-scan"
  | "network/trace/mtr"
  | "network/trace/run"
  | "password/hash/benchmark"
  | "password/hash/crack"
  | "password/hash/generate"
  | "password/hash/identify"
  | "password/hash/mask"
  | "password/hash/rules"
  | "password/hash/verify"
  | "playbook/methodology/catalog"
  | "playbook/methodology/chain"
  | "playbook/methodology/chains"
  | "playbook/methodology/history"
  | "playbook/methodology/list"
  | "playbook/methodology/phases"
  | "playbook/methodology/run"
  | "playbook/methodology/show"
  | "proxy/data/list"
  | "proxy/data/requests"
  | "proxy/data/responses"
  | "proxy/data/show"
  | "proxy/data/stats"
  | "proxy/http/start"
  | "proxy/socks5/start"
  | "proxy/transparent/iptables"
  | "proxy/transparent/nftables"
  | "proxy/transparent/start"
  | "recon/domain/asn"
  | "recon/domain/breach"
  | "recon/domain/describe"
  | "recon/domain/dnsdumpster"
  | "recon/domain/dorks"
  | "recon/domain/email"
  | "recon/domain/full"
  | "recon/domain/get"
  | "recon/domain/graph"
  | "recon/domain/harvest"
  | "recon/domain/list"
  | "recon/domain/massdns"
  | "recon/domain/osint"
  | "recon/domain/rdap"
  | "recon/domain/secrets"
  | "recon/domain/show"
  | "recon/domain/social"
  | "recon/domain/subdomains"
  | "recon/domain/urls"
  | "recon/domain/vuln"
  | "recon/domain/whois"
  | "recon/identity/breach"
  | "recon/identity/email"
  | "recon/identity/username"
  | "report/pentest/generate"
  | "report/pentest/preview"
  | "report/pentest/stats"
  | "search/data/list"
  | "search/data/query"
  | "search/data/stats"
  | "service/manage/install"
  | "service/manage/list"
  | "service/manage/restart"
  | "service/manage/start"
  | "service/manage/status"
  | "service/manage/stop"
  | "service/manage/uninstall"
  | "system/host/inspect"
  | "system/host/summary"
  | "tls/intel/fingerprint"
  | "tls/intel/infrastructure"
  | "tls/intel/scan"
  | "tls/security/audit"
  | "tls/security/ciphers"
  | "tls/security/describe"
  | "tls/security/get"
  | "tls/security/list"
  | "tls/security/mozilla"
  | "tls/security/resume"
  | "tls/security/vuln"
  | "web/asset/cert"
  | "web/asset/cms"
  | "web/asset/cms-scan"
  | "web/asset/crawl"
  | "web/asset/describe"
  | "web/asset/drupal-scan"
  | "web/asset/fingerprint"
  | "web/asset/forms"
  | "web/asset/fuzz"
  | "web/asset/get"
  | "web/asset/grade"
  | "web/asset/har-export"
  | "web/asset/har-replay"
  | "web/asset/har-to-curl"
  | "web/asset/har-view"
  | "web/asset/headers"
  | "web/asset/http2"
  | "web/asset/images"
  | "web/asset/joomla-scan"
  | "web/asset/linkfinder"
  | "web/asset/links"
  | "web/asset/list"
  | "web/asset/meta"
  | "web/asset/scan"
  | "web/asset/scrape"
  | "web/asset/security"
  | "web/asset/tables"
  | "web/asset/vuln-scan"
  | "web/asset/wpscan"
  | "web/fuzz/run"
  | "web/git/dump"
  | "web/git/scan"
  | "web/nosqli/payloads"
  | "web/nosqli/test"
  | "web/sqli/payloads"
  | "web/sqli/tampers"
  | "web/sqli/test"
  | "wordlist/collection/get"
  | "wordlist/collection/info"
  | "wordlist/collection/init"
  | "wordlist/collection/install"
  | "wordlist/collection/list"
  | "wordlist/collection/remove"
  | "wordlist/collection/search"
  | "wordlist/collection/sources"
  | "wordlist/collection/status"
  | "wordlist/collection/update"
  | "wordlist/file/filter"
  | "wordlist/file/info"
;

export type GeneratedRouteTuple =
  | ["access", "system", "file"]
  | ["access", "system", "network"]
  | ["access", "system", "process"]
  | ["access", "system", "registry"]
  | ["access", "system", "service"]
  | ["agent", "c2", "connect"]
  | ["agent", "c2", "server"]
  | ["assess", "target", "run"]
  | ["assess", "target", "show"]
  | ["attack", "target", "apt"]
  | ["attack", "target", "plan"]
  | ["attack", "target", "playbooks"]
  | ["attack", "target", "run"]
  | ["auth", "test", "http"]
  | ["bench", "load", "run"]
  | ["bench", "load", "stress"]
  | ["binary", "analysis", "checksec"]
  | ["binary", "analysis", "find"]
  | ["binary", "analysis", "got"]
  | ["binary", "analysis", "info"]
  | ["binary", "analysis", "pattern"]
  | ["binary", "analysis", "plt"]
  | ["binary", "analysis", "rop"]
  | ["binary", "analysis", "sections"]
  | ["binary", "analysis", "symbols"]
  | ["cloud", "asset", "services"]
  | ["cloud", "asset", "takeover"]
  | ["cloud", "asset", "takeover-scan"]
  | ["cloud", "storage", "enumerate"]
  | ["cloud", "storage", "scan"]
  | ["code", "dependencies", "scan"]
  | ["code", "secrets", "providers"]
  | ["code", "secrets", "scan"]
  | ["code", "secrets", "validate"]
  | ["collect", "browser", "all"]
  | ["collect", "browser", "chrome"]
  | ["collect", "browser", "firefox"]
  | ["collection", "screenshot", "batch"]
  | ["collection", "screenshot", "capture"]
  | ["collection", "screenshot", "http"]
  | ["config", "database", "clear-password"]
  | ["config", "database", "set-password"]
  | ["config", "database", "show"]
  | ["config", "init", "create"]
  | ["crypto", "analyze", "auto"]
  | ["crypto", "analyze", "entropy"]
  | ["crypto", "analyze", "frequency"]
  | ["crypto", "analyze", "hash"]
  | ["crypto", "cipher", "crack"]
  | ["crypto", "cipher", "decrypt"]
  | ["crypto", "cipher", "encrypt"]
  | ["crypto", "cipher", "list"]
  | ["crypto", "codec", "decode"]
  | ["crypto", "codec", "detect"]
  | ["crypto", "codec", "encode"]
  | ["crypto", "codec", "list"]
  | ["crypto", "cyclic", "find"]
  | ["crypto", "cyclic", "generate"]
  | ["crypto", "cyclic", "offset"]
  | ["crypto", "hash", "verify"]
  | ["crypto", "recipe", "bake"]
  | ["crypto", "recipe", "run"]
  | ["crypto", "vault", "decrypt"]
  | ["crypto", "vault", "encrypt"]
  | ["crypto", "vault", "info"]
  | ["database", "engine", "checkpoint"]
  | ["database", "engine", "info"]
  | ["database", "engine", "open"]
  | ["database", "engine", "stats"]
  | ["database", "query", "dns"]
  | ["database", "query", "hosts"]
  | ["database", "query", "http"]
  | ["database", "query", "ports"]
  | ["database", "query", "subdomains"]
  | ["database", "query", "summary"]
  | ["database", "query", "tls"]
  | ["database", "query", "whois"]
  | ["database", "vector", "index"]
  | ["database", "vector", "info"]
  | ["database", "vector", "search"]
  | ["dns", "record", "all"]
  | ["dns", "record", "bruteforce"]
  | ["dns", "record", "describe"]
  | ["dns", "record", "email"]
  | ["dns", "record", "get"]
  | ["dns", "record", "list"]
  | ["dns", "record", "lookup"]
  | ["dns", "record", "propagation"]
  | ["dns", "record", "resolve"]
  | ["dns", "record", "reverse"]
  | ["dns", "server", "block"]
  | ["dns", "server", "hijack"]
  | ["dns", "server", "start"]
  | ["docs", "kb", "index"]
  | ["docs", "kb", "search"]
  | ["evasion", "amsi", "csharp"]
  | ["evasion", "amsi", "obfuscated"]
  | ["evasion", "amsi", "powershell"]
  | ["evasion", "amsi", "providers"]
  | ["evasion", "antidebug", "check"]
  | ["evasion", "antidebug", "paranoid"]
  | ["evasion", "antidebug", "quick"]
  | ["evasion", "apihash", "hash"]
  | ["evasion", "apihash", "list"]
  | ["evasion", "apihash", "syscalls"]
  | ["evasion", "build", "deobfuscate"]
  | ["evasion", "build", "info"]
  | ["evasion", "build", "obfuscate"]
  | ["evasion", "build", "rehash"]
  | ["evasion", "config", "aggressive"]
  | ["evasion", "config", "default"]
  | ["evasion", "config", "show"]
  | ["evasion", "config", "stealth"]
  | ["evasion", "controlflow", "demo"]
  | ["evasion", "controlflow", "predicates"]
  | ["evasion", "controlflow", "substitute"]
  | ["evasion", "inject", "encode"]
  | ["evasion", "inject", "list"]
  | ["evasion", "inject", "shellcode"]
  | ["evasion", "memory", "demo"]
  | ["evasion", "memory", "encrypt"]
  | ["evasion", "memory", "heap"]
  | ["evasion", "memory", "rotate"]
  | ["evasion", "memory", "sleep"]
  | ["evasion", "memory", "vault"]
  | ["evasion", "network", "jitter"]
  | ["evasion", "network", "shape"]
  | ["evasion", "network", "timer"]
  | ["evasion", "obfuscate", "base64"]
  | ["evasion", "obfuscate", "deobfuscate"]
  | ["evasion", "obfuscate", "rot"]
  | ["evasion", "obfuscate", "xor"]
  | ["evasion", "sandbox", "check"]
  | ["evasion", "sandbox", "delay"]
  | ["evasion", "sandbox", "score"]
  | ["evasion", "strings", "demo"]
  | ["evasion", "strings", "encrypt"]
  | ["evasion", "strings", "sensitive"]
  | ["evasion", "tracks", "clear"]
  | ["evasion", "tracks", "command"]
  | ["evasion", "tracks", "scan"]
  | ["evasion", "tracks", "sessions"]
  | ["exploit", "browser", "exec"]
  | ["exploit", "browser", "list"]
  | ["exploit", "browser", "serve"]
  | ["exploit", "payload", "apt"]
  | ["exploit", "payload", "dns-shell"]
  | ["exploit", "payload", "encrypted-shell"]
  | ["exploit", "payload", "http-shell"]
  | ["exploit", "payload", "icmp-shell"]
  | ["exploit", "payload", "lateral"]
  | ["exploit", "payload", "listener"]
  | ["exploit", "payload", "multi-shell"]
  | ["exploit", "payload", "persist"]
  | ["exploit", "payload", "plan"]
  | ["exploit", "payload", "playbooks"]
  | ["exploit", "payload", "privesc"]
  | ["exploit", "payload", "recommend"]
  | ["exploit", "payload", "replicate"]
  | ["exploit", "payload", "run"]
  | ["exploit", "payload", "sessions"]
  | ["exploit", "payload", "shell"]
  | ["exploit", "payload", "start"]
  | ["exploit", "payload", "suggest"]
  | ["exploit", "payload", "websocket-shell"]
  | ["exploit", "phish", "clone"]
  | ["exploit", "phish", "email"]
  | ["exploit", "phish", "serve"]
  | ["exploit", "phish", "templates"]
  | ["file", "ops", "hash"]
  | ["file", "ops", "info"]
  | ["file", "ops", "unzip"]
  | ["file", "ops", "zip"]
  | ["hex", "file", "compare"]
  | ["hex", "file", "info"]
  | ["hex", "file", "inspect"]
  | ["hex", "file", "read"]
  | ["hex", "file", "replace"]
  | ["hex", "file", "search"]
  | ["hex", "file", "view"]
  | ["hex", "file", "write"]
  | ["http", "server", "payloads"]
  | ["http", "server", "serve"]
  | ["intelligence", "graph", "centrality"]
  | ["intelligence", "graph", "cert"]
  | ["intelligence", "graph", "communities"]
  | ["intelligence", "graph", "components"]
  | ["intelligence", "graph", "credential"]
  | ["intelligence", "graph", "cycles"]
  | ["intelligence", "graph", "domain"]
  | ["intelligence", "graph", "export"]
  | ["intelligence", "graph", "host"]
  | ["intelligence", "graph", "import"]
  | ["intelligence", "graph", "insights"]
  | ["intelligence", "graph", "network"]
  | ["intelligence", "graph", "pagerank"]
  | ["intelligence", "graph", "paths"]
  | ["intelligence", "graph", "query"]
  | ["intelligence", "graph", "report"]
  | ["intelligence", "graph", "rql"]
  | ["intelligence", "graph", "service"]
  | ["intelligence", "graph", "stats"]
  | ["intelligence", "graph", "summary"]
  | ["intelligence", "graph", "tech"]
  | ["intelligence", "graph", "user"]
  | ["intelligence", "graph", "viz"]
  | ["intelligence", "graph", "vuln"]
  | ["intelligence", "ioc", "demo"]
  | ["intelligence", "ioc", "export"]
  | ["intelligence", "ioc", "extract"]
  | ["intelligence", "ioc", "import"]
  | ["intelligence", "ioc", "search"]
  | ["intelligence", "ioc", "types"]
  | ["intelligence", "mitre", "cache"]
  | ["intelligence", "mitre", "correlate"]
  | ["intelligence", "mitre", "coverage"]
  | ["intelligence", "mitre", "detection"]
  | ["intelligence", "mitre", "export"]
  | ["intelligence", "mitre", "gaps"]
  | ["intelligence", "mitre", "group"]
  | ["intelligence", "mitre", "map"]
  | ["intelligence", "mitre", "matrix"]
  | ["intelligence", "mitre", "mitigations"]
  | ["intelligence", "mitre", "navigator"]
  | ["intelligence", "mitre", "ports"]
  | ["intelligence", "mitre", "search"]
  | ["intelligence", "mitre", "software"]
  | ["intelligence", "mitre", "stats"]
  | ["intelligence", "mitre", "tactic"]
  | ["intelligence", "mitre", "technique"]
  | ["intelligence", "taxii", "collections"]
  | ["intelligence", "taxii", "sync"]
  | ["intelligence", "vuln", "correlate"]
  | ["intelligence", "vuln", "cpe"]
  | ["intelligence", "vuln", "cve"]
  | ["intelligence", "vuln", "exploit"]
  | ["intelligence", "vuln", "kev"]
  | ["intelligence", "vuln", "report"]
  | ["intelligence", "vuln", "scan"]
  | ["intelligence", "vuln", "search"]
  | ["loot", "entry", "add"]
  | ["loot", "entry", "delete"]
  | ["loot", "entry", "export"]
  | ["loot", "entry", "list"]
  | ["loot", "entry", "show"]
  | ["loot", "entry", "stats"]
  | ["loot", "graph", "insights"]
  | ["loot", "graph", "paths"]
  | ["loot", "graph", "rebuild"]
  | ["loot", "graph", "show"]
  | ["loot", "graph", "stats"]
  | ["mcp", "server", "start"]
  | ["memory", "process", "aob"]
  | ["memory", "process", "dump"]
  | ["memory", "process", "list"]
  | ["memory", "process", "maps"]
  | ["memory", "process", "read"]
  | ["memory", "process", "scan"]
  | ["memory", "process", "string"]
  | ["memory", "process", "write"]
  | ["mitm", "intercept", "dns"]
  | ["mitm", "intercept", "export-ca"]
  | ["mitm", "intercept", "generate-ca"]
  | ["mitm", "intercept", "proxy"]
  | ["mitm", "intercept", "shell"]
  | ["mitm", "intercept", "start"]
  | ["network", "health", "check"]
  | ["network", "health", "diff"]
  | ["network", "health", "watch"]
  | ["network", "host", "discover"]
  | ["network", "host", "fingerprint"]
  | ["network", "host", "intel"]
  | ["network", "host", "list"]
  | ["network", "host", "ping"]
  | ["network", "nc", "broker"]
  | ["network", "nc", "connect"]
  | ["network", "nc", "listen"]
  | ["network", "nc", "relay"]
  | ["network", "nc", "scan"]
  | ["network", "ports", "mass-scan"]
  | ["network", "ports", "range"]
  | ["network", "ports", "scan"]
  | ["network", "ports", "stealth"]
  | ["network", "ports", "subnet"]
  | ["network", "ports", "syn-scan"]
  | ["network", "ports", "udp-scan"]
  | ["network", "trace", "mtr"]
  | ["network", "trace", "run"]
  | ["password", "hash", "benchmark"]
  | ["password", "hash", "crack"]
  | ["password", "hash", "generate"]
  | ["password", "hash", "identify"]
  | ["password", "hash", "mask"]
  | ["password", "hash", "rules"]
  | ["password", "hash", "verify"]
  | ["playbook", "methodology", "catalog"]
  | ["playbook", "methodology", "chain"]
  | ["playbook", "methodology", "chains"]
  | ["playbook", "methodology", "history"]
  | ["playbook", "methodology", "list"]
  | ["playbook", "methodology", "phases"]
  | ["playbook", "methodology", "run"]
  | ["playbook", "methodology", "show"]
  | ["proxy", "data", "list"]
  | ["proxy", "data", "requests"]
  | ["proxy", "data", "responses"]
  | ["proxy", "data", "show"]
  | ["proxy", "data", "stats"]
  | ["proxy", "http", "start"]
  | ["proxy", "socks5", "start"]
  | ["proxy", "transparent", "iptables"]
  | ["proxy", "transparent", "nftables"]
  | ["proxy", "transparent", "start"]
  | ["recon", "domain", "asn"]
  | ["recon", "domain", "breach"]
  | ["recon", "domain", "describe"]
  | ["recon", "domain", "dnsdumpster"]
  | ["recon", "domain", "dorks"]
  | ["recon", "domain", "email"]
  | ["recon", "domain", "full"]
  | ["recon", "domain", "get"]
  | ["recon", "domain", "graph"]
  | ["recon", "domain", "harvest"]
  | ["recon", "domain", "list"]
  | ["recon", "domain", "massdns"]
  | ["recon", "domain", "osint"]
  | ["recon", "domain", "rdap"]
  | ["recon", "domain", "secrets"]
  | ["recon", "domain", "show"]
  | ["recon", "domain", "social"]
  | ["recon", "domain", "subdomains"]
  | ["recon", "domain", "urls"]
  | ["recon", "domain", "vuln"]
  | ["recon", "domain", "whois"]
  | ["recon", "identity", "breach"]
  | ["recon", "identity", "email"]
  | ["recon", "identity", "username"]
  | ["report", "pentest", "generate"]
  | ["report", "pentest", "preview"]
  | ["report", "pentest", "stats"]
  | ["search", "data", "list"]
  | ["search", "data", "query"]
  | ["search", "data", "stats"]
  | ["service", "manage", "install"]
  | ["service", "manage", "list"]
  | ["service", "manage", "restart"]
  | ["service", "manage", "start"]
  | ["service", "manage", "status"]
  | ["service", "manage", "stop"]
  | ["service", "manage", "uninstall"]
  | ["system", "host", "inspect"]
  | ["system", "host", "summary"]
  | ["tls", "intel", "fingerprint"]
  | ["tls", "intel", "infrastructure"]
  | ["tls", "intel", "scan"]
  | ["tls", "security", "audit"]
  | ["tls", "security", "ciphers"]
  | ["tls", "security", "describe"]
  | ["tls", "security", "get"]
  | ["tls", "security", "list"]
  | ["tls", "security", "mozilla"]
  | ["tls", "security", "resume"]
  | ["tls", "security", "vuln"]
  | ["web", "asset", "cert"]
  | ["web", "asset", "cms"]
  | ["web", "asset", "cms-scan"]
  | ["web", "asset", "crawl"]
  | ["web", "asset", "describe"]
  | ["web", "asset", "drupal-scan"]
  | ["web", "asset", "fingerprint"]
  | ["web", "asset", "forms"]
  | ["web", "asset", "fuzz"]
  | ["web", "asset", "get"]
  | ["web", "asset", "grade"]
  | ["web", "asset", "har-export"]
  | ["web", "asset", "har-replay"]
  | ["web", "asset", "har-to-curl"]
  | ["web", "asset", "har-view"]
  | ["web", "asset", "headers"]
  | ["web", "asset", "http2"]
  | ["web", "asset", "images"]
  | ["web", "asset", "joomla-scan"]
  | ["web", "asset", "linkfinder"]
  | ["web", "asset", "links"]
  | ["web", "asset", "list"]
  | ["web", "asset", "meta"]
  | ["web", "asset", "scan"]
  | ["web", "asset", "scrape"]
  | ["web", "asset", "security"]
  | ["web", "asset", "tables"]
  | ["web", "asset", "vuln-scan"]
  | ["web", "asset", "wpscan"]
  | ["web", "fuzz", "run"]
  | ["web", "git", "dump"]
  | ["web", "git", "scan"]
  | ["web", "nosqli", "payloads"]
  | ["web", "nosqli", "test"]
  | ["web", "sqli", "payloads"]
  | ["web", "sqli", "tampers"]
  | ["web", "sqli", "test"]
  | ["wordlist", "collection", "get"]
  | ["wordlist", "collection", "info"]
  | ["wordlist", "collection", "init"]
  | ["wordlist", "collection", "install"]
  | ["wordlist", "collection", "list"]
  | ["wordlist", "collection", "remove"]
  | ["wordlist", "collection", "search"]
  | ["wordlist", "collection", "sources"]
  | ["wordlist", "collection", "status"]
  | ["wordlist", "collection", "update"]
  | ["wordlist", "file", "filter"]
  | ["wordlist", "file", "info"]
;

export interface GeneratedRouteSurface<TInvocation = unknown> {
  "access": {
    "system": {
      "file": TInvocation;
      "network": TInvocation;
      "process": TInvocation;
      "registry": TInvocation;
      "service": TInvocation;
    };
  };
  "agent": {
    "c2": {
      "connect": TInvocation;
      "server": TInvocation;
    };
  };
  "assess": {
    "target": {
      "run": TInvocation;
      "show": TInvocation;
    };
  };
  "attack": {
    "target": {
      "apt": TInvocation;
      "plan": TInvocation;
      "playbooks": TInvocation;
      "run": TInvocation;
    };
  };
  "auth": {
    "test": {
      "http": TInvocation;
    };
  };
  "bench": {
    "load": {
      "run": TInvocation;
      "stress": TInvocation;
    };
  };
  "binary": {
    "analysis": {
      "checksec": TInvocation;
      "find": TInvocation;
      "got": TInvocation;
      "info": TInvocation;
      "pattern": TInvocation;
      "plt": TInvocation;
      "rop": TInvocation;
      "sections": TInvocation;
      "symbols": TInvocation;
    };
  };
  "cloud": {
    "asset": {
      "services": TInvocation;
      "takeover": TInvocation;
      "takeover-scan": TInvocation;
    };
    "storage": {
      "enumerate": TInvocation;
      "scan": TInvocation;
    };
  };
  "code": {
    "dependencies": {
      "scan": TInvocation;
    };
    "secrets": {
      "providers": TInvocation;
      "scan": TInvocation;
      "validate": TInvocation;
    };
  };
  "collect": {
    "browser": {
      "all": TInvocation;
      "chrome": TInvocation;
      "firefox": TInvocation;
    };
  };
  "collection": {
    "screenshot": {
      "batch": TInvocation;
      "capture": TInvocation;
      "http": TInvocation;
    };
  };
  "config": {
    "database": {
      "clear-password": TInvocation;
      "set-password": TInvocation;
      "show": TInvocation;
    };
    "init": {
      "create": TInvocation;
    };
  };
  "crypto": {
    "analyze": {
      "auto": TInvocation;
      "entropy": TInvocation;
      "frequency": TInvocation;
      "hash": TInvocation;
    };
    "cipher": {
      "crack": TInvocation;
      "decrypt": TInvocation;
      "encrypt": TInvocation;
      "list": TInvocation;
    };
    "codec": {
      "decode": TInvocation;
      "detect": TInvocation;
      "encode": TInvocation;
      "list": TInvocation;
    };
    "cyclic": {
      "find": TInvocation;
      "generate": TInvocation;
      "offset": TInvocation;
    };
    "hash": {
      "verify": TInvocation;
    };
    "recipe": {
      "bake": TInvocation;
      "run": TInvocation;
    };
    "vault": {
      "decrypt": TInvocation;
      "encrypt": TInvocation;
      "info": TInvocation;
    };
  };
  "database": {
    "engine": {
      "checkpoint": TInvocation;
      "info": TInvocation;
      "open": TInvocation;
      "stats": TInvocation;
    };
    "query": {
      "dns": TInvocation;
      "hosts": TInvocation;
      "http": TInvocation;
      "ports": TInvocation;
      "subdomains": TInvocation;
      "summary": TInvocation;
      "tls": TInvocation;
      "whois": TInvocation;
    };
    "vector": {
      "index": TInvocation;
      "info": TInvocation;
      "search": TInvocation;
    };
  };
  "dns": {
    "record": {
      "all": TInvocation;
      "bruteforce": TInvocation;
      "describe": TInvocation;
      "email": TInvocation;
      "get": TInvocation;
      "list": TInvocation;
      "lookup": TInvocation;
      "propagation": TInvocation;
      "resolve": TInvocation;
      "reverse": TInvocation;
    };
    "server": {
      "block": TInvocation;
      "hijack": TInvocation;
      "start": TInvocation;
    };
  };
  "docs": {
    "kb": {
      "index": TInvocation;
      "search": TInvocation;
    };
  };
  "evasion": {
    "amsi": {
      "csharp": TInvocation;
      "obfuscated": TInvocation;
      "powershell": TInvocation;
      "providers": TInvocation;
    };
    "antidebug": {
      "check": TInvocation;
      "paranoid": TInvocation;
      "quick": TInvocation;
    };
    "apihash": {
      "hash": TInvocation;
      "list": TInvocation;
      "syscalls": TInvocation;
    };
    "build": {
      "deobfuscate": TInvocation;
      "info": TInvocation;
      "obfuscate": TInvocation;
      "rehash": TInvocation;
    };
    "config": {
      "aggressive": TInvocation;
      "default": TInvocation;
      "show": TInvocation;
      "stealth": TInvocation;
    };
    "controlflow": {
      "demo": TInvocation;
      "predicates": TInvocation;
      "substitute": TInvocation;
    };
    "inject": {
      "encode": TInvocation;
      "list": TInvocation;
      "shellcode": TInvocation;
    };
    "memory": {
      "demo": TInvocation;
      "encrypt": TInvocation;
      "heap": TInvocation;
      "rotate": TInvocation;
      "sleep": TInvocation;
      "vault": TInvocation;
    };
    "network": {
      "jitter": TInvocation;
      "shape": TInvocation;
      "timer": TInvocation;
    };
    "obfuscate": {
      "base64": TInvocation;
      "deobfuscate": TInvocation;
      "rot": TInvocation;
      "xor": TInvocation;
    };
    "sandbox": {
      "check": TInvocation;
      "delay": TInvocation;
      "score": TInvocation;
    };
    "strings": {
      "demo": TInvocation;
      "encrypt": TInvocation;
      "sensitive": TInvocation;
    };
    "tracks": {
      "clear": TInvocation;
      "command": TInvocation;
      "scan": TInvocation;
      "sessions": TInvocation;
    };
  };
  "exploit": {
    "browser": {
      "exec": TInvocation;
      "list": TInvocation;
      "serve": TInvocation;
    };
    "payload": {
      "apt": TInvocation;
      "dns-shell": TInvocation;
      "encrypted-shell": TInvocation;
      "http-shell": TInvocation;
      "icmp-shell": TInvocation;
      "lateral": TInvocation;
      "listener": TInvocation;
      "multi-shell": TInvocation;
      "persist": TInvocation;
      "plan": TInvocation;
      "playbooks": TInvocation;
      "privesc": TInvocation;
      "recommend": TInvocation;
      "replicate": TInvocation;
      "run": TInvocation;
      "sessions": TInvocation;
      "shell": TInvocation;
      "start": TInvocation;
      "suggest": TInvocation;
      "websocket-shell": TInvocation;
    };
    "phish": {
      "clone": TInvocation;
      "email": TInvocation;
      "serve": TInvocation;
      "templates": TInvocation;
    };
  };
  "file": {
    "ops": {
      "hash": TInvocation;
      "info": TInvocation;
      "unzip": TInvocation;
      "zip": TInvocation;
    };
  };
  "hex": {
    "file": {
      "compare": TInvocation;
      "info": TInvocation;
      "inspect": TInvocation;
      "read": TInvocation;
      "replace": TInvocation;
      "search": TInvocation;
      "view": TInvocation;
      "write": TInvocation;
    };
  };
  "http": {
    "server": {
      "payloads": TInvocation;
      "serve": TInvocation;
    };
  };
  "intelligence": {
    "graph": {
      "centrality": TInvocation;
      "cert": TInvocation;
      "communities": TInvocation;
      "components": TInvocation;
      "credential": TInvocation;
      "cycles": TInvocation;
      "domain": TInvocation;
      "export": TInvocation;
      "host": TInvocation;
      "import": TInvocation;
      "insights": TInvocation;
      "network": TInvocation;
      "pagerank": TInvocation;
      "paths": TInvocation;
      "query": TInvocation;
      "report": TInvocation;
      "rql": TInvocation;
      "service": TInvocation;
      "stats": TInvocation;
      "summary": TInvocation;
      "tech": TInvocation;
      "user": TInvocation;
      "viz": TInvocation;
      "vuln": TInvocation;
    };
    "ioc": {
      "demo": TInvocation;
      "export": TInvocation;
      "extract": TInvocation;
      "import": TInvocation;
      "search": TInvocation;
      "types": TInvocation;
    };
    "mitre": {
      "cache": TInvocation;
      "correlate": TInvocation;
      "coverage": TInvocation;
      "detection": TInvocation;
      "export": TInvocation;
      "gaps": TInvocation;
      "group": TInvocation;
      "map": TInvocation;
      "matrix": TInvocation;
      "mitigations": TInvocation;
      "navigator": TInvocation;
      "ports": TInvocation;
      "search": TInvocation;
      "software": TInvocation;
      "stats": TInvocation;
      "tactic": TInvocation;
      "technique": TInvocation;
    };
    "taxii": {
      "collections": TInvocation;
      "sync": TInvocation;
    };
    "vuln": {
      "correlate": TInvocation;
      "cpe": TInvocation;
      "cve": TInvocation;
      "exploit": TInvocation;
      "kev": TInvocation;
      "report": TInvocation;
      "scan": TInvocation;
      "search": TInvocation;
    };
  };
  "loot": {
    "entry": {
      "add": TInvocation;
      "delete": TInvocation;
      "export": TInvocation;
      "list": TInvocation;
      "show": TInvocation;
      "stats": TInvocation;
    };
    "graph": {
      "insights": TInvocation;
      "paths": TInvocation;
      "rebuild": TInvocation;
      "show": TInvocation;
      "stats": TInvocation;
    };
  };
  "mcp": {
    "server": {
      "start": TInvocation;
    };
  };
  "memory": {
    "process": {
      "aob": TInvocation;
      "dump": TInvocation;
      "list": TInvocation;
      "maps": TInvocation;
      "read": TInvocation;
      "scan": TInvocation;
      "string": TInvocation;
      "write": TInvocation;
    };
  };
  "mitm": {
    "intercept": {
      "dns": TInvocation;
      "export-ca": TInvocation;
      "generate-ca": TInvocation;
      "proxy": TInvocation;
      "shell": TInvocation;
      "start": TInvocation;
    };
  };
  "network": {
    "health": {
      "check": TInvocation;
      "diff": TInvocation;
      "watch": TInvocation;
    };
    "host": {
      "discover": TInvocation;
      "fingerprint": TInvocation;
      "intel": TInvocation;
      "list": TInvocation;
      "ping": TInvocation;
    };
    "nc": {
      "broker": TInvocation;
      "connect": TInvocation;
      "listen": TInvocation;
      "relay": TInvocation;
      "scan": TInvocation;
    };
    "ports": {
      "mass-scan": TInvocation;
      "range": TInvocation;
      "scan": TInvocation;
      "stealth": TInvocation;
      "subnet": TInvocation;
      "syn-scan": TInvocation;
      "udp-scan": TInvocation;
    };
    "trace": {
      "mtr": TInvocation;
      "run": TInvocation;
    };
  };
  "password": {
    "hash": {
      "benchmark": TInvocation;
      "crack": TInvocation;
      "generate": TInvocation;
      "identify": TInvocation;
      "mask": TInvocation;
      "rules": TInvocation;
      "verify": TInvocation;
    };
  };
  "playbook": {
    "methodology": {
      "catalog": TInvocation;
      "chain": TInvocation;
      "chains": TInvocation;
      "history": TInvocation;
      "list": TInvocation;
      "phases": TInvocation;
      "run": TInvocation;
      "show": TInvocation;
    };
  };
  "proxy": {
    "data": {
      "list": TInvocation;
      "requests": TInvocation;
      "responses": TInvocation;
      "show": TInvocation;
      "stats": TInvocation;
    };
    "http": {
      "start": TInvocation;
    };
    "socks5": {
      "start": TInvocation;
    };
    "transparent": {
      "iptables": TInvocation;
      "nftables": TInvocation;
      "start": TInvocation;
    };
  };
  "recon": {
    "domain": {
      "asn": TInvocation;
      "breach": TInvocation;
      "describe": TInvocation;
      "dnsdumpster": TInvocation;
      "dorks": TInvocation;
      "email": TInvocation;
      "full": TInvocation;
      "get": TInvocation;
      "graph": TInvocation;
      "harvest": TInvocation;
      "list": TInvocation;
      "massdns": TInvocation;
      "osint": TInvocation;
      "rdap": TInvocation;
      "secrets": TInvocation;
      "show": TInvocation;
      "social": TInvocation;
      "subdomains": TInvocation;
      "urls": TInvocation;
      "vuln": TInvocation;
      "whois": TInvocation;
    };
    "identity": {
      "breach": TInvocation;
      "email": TInvocation;
      "username": TInvocation;
    };
  };
  "report": {
    "pentest": {
      "generate": TInvocation;
      "preview": TInvocation;
      "stats": TInvocation;
    };
  };
  "search": {
    "data": {
      "list": TInvocation;
      "query": TInvocation;
      "stats": TInvocation;
    };
  };
  "service": {
    "manage": {
      "install": TInvocation;
      "list": TInvocation;
      "restart": TInvocation;
      "start": TInvocation;
      "status": TInvocation;
      "stop": TInvocation;
      "uninstall": TInvocation;
    };
  };
  "system": {
    "host": {
      "inspect": TInvocation;
      "summary": TInvocation;
    };
  };
  "tls": {
    "intel": {
      "fingerprint": TInvocation;
      "infrastructure": TInvocation;
      "scan": TInvocation;
    };
    "security": {
      "audit": TInvocation;
      "ciphers": TInvocation;
      "describe": TInvocation;
      "get": TInvocation;
      "list": TInvocation;
      "mozilla": TInvocation;
      "resume": TInvocation;
      "vuln": TInvocation;
    };
  };
  "web": {
    "asset": {
      "cert": TInvocation;
      "cms": TInvocation;
      "cms-scan": TInvocation;
      "crawl": TInvocation;
      "describe": TInvocation;
      "drupal-scan": TInvocation;
      "fingerprint": TInvocation;
      "forms": TInvocation;
      "fuzz": TInvocation;
      "get": TInvocation;
      "grade": TInvocation;
      "har-export": TInvocation;
      "har-replay": TInvocation;
      "har-to-curl": TInvocation;
      "har-view": TInvocation;
      "headers": TInvocation;
      "http2": TInvocation;
      "images": TInvocation;
      "joomla-scan": TInvocation;
      "linkfinder": TInvocation;
      "links": TInvocation;
      "list": TInvocation;
      "meta": TInvocation;
      "scan": TInvocation;
      "scrape": TInvocation;
      "security": TInvocation;
      "tables": TInvocation;
      "vuln-scan": TInvocation;
      "wpscan": TInvocation;
    };
    "fuzz": {
      "run": TInvocation;
    };
    "git": {
      "dump": TInvocation;
      "scan": TInvocation;
    };
    "nosqli": {
      "payloads": TInvocation;
      "test": TInvocation;
    };
    "sqli": {
      "payloads": TInvocation;
      "tampers": TInvocation;
      "test": TInvocation;
    };
  };
  "wordlist": {
    "collection": {
      "get": TInvocation;
      "info": TInvocation;
      "init": TInvocation;
      "install": TInvocation;
      "list": TInvocation;
      "remove": TInvocation;
      "search": TInvocation;
      "sources": TInvocation;
      "status": TInvocation;
      "update": TInvocation;
    };
    "file": {
      "filter": TInvocation;
      "info": TInvocation;
    };
  };
}
export interface GeneratedRouteContract {
  schema_version: number;
  manifest_version: string;
  route_count: number;
  routes: GeneratedCanonicalRoutePath[];
}
